/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActivityHistoryDetailDialog: typeof import('./resources/ts/layouts/dialogs/histories/ActivityHistoryDetailDialog.vue')['default']
    ActivityHistoryTargetDialog: typeof import('./resources/ts/layouts/dialogs/histories/ActivityHistoryTargetDialog.vue')['default']
    AlertDialog: typeof import('./resources/ts/layouts/dialogs/utils/AlertDialog.vue')['default']
    AppAutocomplete: typeof import('./resources/ts/@core/components/app-form-elements/AppAutocomplete.vue')['default']
    AppCardActions: typeof import('./resources/ts/@core/components/AppCardActions.vue')['default']
    AppCombobox: typeof import('./resources/ts/@core/components/app-form-elements/AppCombobox.vue')['default']
    AppDateTimePicker: typeof import('./resources/ts/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/ts/@core/components/AppDrawerHeaderSection.vue')['default']
    AppSelect: typeof import('./resources/ts/@core/components/app-form-elements/AppSelect.vue')['default']
    AppStepper: typeof import('./resources/ts/@core/components/AppStepper.vue')['default']
    AppTextarea: typeof import('./resources/ts/@core/components/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./resources/ts/@core/components/app-form-elements/AppTextField.vue')['default']
    BankAccountDialog: typeof import('./resources/ts/layouts/dialogs/bulks/BankAccountDialog.vue')['default']
    CancelPartDialog: typeof import('./resources/ts/layouts/dialogs/transactions/CancelPartDialog.vue')['default']
    CustomCheckboxes: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithImage.vue')['default']
    CustomizerSection: typeof import('./resources/ts/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
    DetailWorkStatusDialog: typeof import('./resources/ts/layouts/dialogs/utils/DetailWorkStatusDialog.vue')['default']
    DialogCloseBtn: typeof import('./resources/ts/@core/components/DialogCloseBtn.vue')['default']
    ErrorHeader: typeof import('./resources/ts/@core/components/ErrorHeader.vue')['default']
    ExceptionWorkTimeDialog: typeof import('./resources/ts/layouts/dialogs/services/ExceptionWorkTimeDialog.vue')['default']
    Google2FACreateDialog: typeof import('./resources/ts/layouts/dialogs/users/Google2FACreateDialog.vue')['default']
    Google2FAVertifyDialog: typeof import('./resources/ts/layouts/dialogs/users/Google2FAVertifyDialog.vue')['default']
    I18n: typeof import('./resources/ts/@core/components/I18n.vue')['default']
    ImageDialog: typeof import('./resources/ts/layouts/dialogs/utils/ImageDialog.vue')['default']
    IPDetailDialog: typeof import('./resources/ts/layouts/dialogs/services/IPDetailDialog.vue')['default']
    LastLoginDialog: typeof import('./resources/ts/layouts/dialogs/services/LastLoginDialog.vue')['default']
    LoadingDialog: typeof import('./resources/ts/layouts/dialogs/utils/LoadingDialog.vue')['default']
    LoginImageDialog: typeof import('./resources/ts/layouts/dialogs/services/LoginImageDialog.vue')['default']
    MobileVerification: typeof import('./resources/ts/@core/components/MobileVerification.vue')['default']
    Notifications: typeof import('./resources/ts/@core/components/Notifications.vue')['default']
    OperatorDialog: typeof import('./resources/ts/layouts/dialogs/users/OperatorDialog.vue')['default']
    OperatorIPDialog: typeof import('./resources/ts/layouts/dialogs/services/OperatorIPDialog.vue')['default']
    PasswordAuthDialog: typeof import('./resources/ts/layouts/dialogs/users/PasswordAuthDialog.vue')['default']
    PasswordChangeDialog: typeof import('./resources/ts/layouts/dialogs/users/PasswordChangeDialog.vue')['default']
    PasswordChangeNoticeDialog: typeof import('./resources/ts/layouts/dialogs/users/PasswordChangeNoticeDialog.vue')['default']
    PasswordCheckDialog: typeof import('./resources/ts/layouts/dialogs/users/PasswordCheckDialog.vue')['default']
    PhoneNum2FAVertifyDialog: typeof import('./resources/ts/layouts/dialogs/users/PhoneNum2FAVertifyDialog.vue')['default']
    ProfileDialog: typeof import('./resources/ts/layouts/dialogs/users/ProfileDialog.vue')['default']
    PVWithdrawErrorCodeDialog: typeof import('./resources/ts/layouts/dialogs/cms-transactions/PVWithdrawErrorCodeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterDialog: typeof import('./resources/ts/layouts/dialogs/utils/SearchFilterDialog.vue')['default']
    SecureReportDialog: typeof import('./resources/ts/layouts/dialogs/utils/SecureReportDialog.vue')['default']
    SettlementInformationDialog: typeof import('./resources/ts/layouts/dialogs/bulks/SettlementInformationDialog.vue')['default']
    TheCustomizer: typeof import('./resources/ts/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    VanWithdrawErrorCodeDialog: typeof import('./resources/ts/layouts/dialogs/cms-transactions/finance-vans-error-codes/VanWithdrawErrorCodeDialog.vue')['default']
    WithdrawHistoriesDialog: typeof import('./resources/ts/layouts/dialogs/cms-transactions/WithdrawHistoriesDialog.vue')['default']
  }
}
