<?php

namespace App\Jobs\Realtime\Coocon;
use App\Jobs\Realtime\RealtimeFDS;
use Illuminate\Support\Facades\Log;

class Coocon extends RealtimeFDS
{
    public $is_test, $host, $auth_host, $timeout_codes;
    public function __construct($finance_van, $privacy, $deposit_type, $withdraw_book_time)
    {
        parent::__construct($finance_van, $privacy, $deposit_type, $withdraw_book_time);
        $this->is_test  = $finance_van['withdraw_acct_num'] === "0000000000000000" ? true : false;
        $this->host     = "https://".($this->is_test ? "dev2.coocon.co.kr:8443" : "apigw.coocon.co.kr")."/sol/gateway/vapg_wapi.jsp";
        $this->auth_host     = "https://".($this->is_test ? "iris-uat" : "iris").".coocon.co.kr";
        $this->timeout_codes = ['9980', 'P413', '-500', '001'];
    }

    public function init($infos)
    {
        parent::init($infos);
    }

    // 실제로 출금 요청을 보내는 부분
    protected function send($params)
    {
        $res = $this->asPost($this->host, ['JSONData'=> json_encode($params)], []);
        if($res['code'] === 200)
        {   // 출금 요청 성공시
            $res = $res['body'];
            if($res['RESP_CD'] === "0000")
            {   // 응답 코드가 0000일때
                if($params['KEY'] === "6120")
                    $res['RESP_MSG'] = "이체 요청";
                else if($params['KEY'] === "6140")
                    $res['RESP_MSG'] = "잔액 조회 성공";
                else if($params['KEY'] === "6170")
                {   // 응답키가 6170이면서 상태가 1이면 이체 성공
                    if($res['STS'] === 1)
                        $res['RESP_MSG'] = "이체 성공";
                    else if($res['STS'] === 3)
                    {   // 상태가 3이면 에러
                        $res['RESP_CD'] === "-1000";
                        $res['RESP_MSG'] = "이체 에러";
                    }
                    else if($res['STS'] === 6)
                        $res['RESP_MSG'] = "이체 처리중";
                }
            }
            else
            {
                $res['RESP_MSG'] = isset($res['RESP_MSG']) ? $res['RESP_MSG'] : '';
                $res['RESP_MSG'] = $this->getErrorMessage($res['RESP_CD'], $res['RESP_MSG']);
            }
            return $res;
        }
        else
        {   // 출금 요청 실패시
            $res = $res['body'];
            $message = isset($res['RESP_MSG']) ? $res['RESP_MSG'] : '타임아웃';
            $body = [
                'RESP_CD' => '-500',
                'RESP_MSG' => $message,
            ];

            Log::warning("coocon finance van warning", array_merge([
                'key' => $params['KEY']
            ], $res['body']));

            return $body;
        }
    }

    protected function getAuthParams()
    {
        return [
            "SECR_KEY"      => $this->finance_van['api_key'],
            "TRT_INST_CD"   => $this->finance_van['corp_code'],
            "BANK_CD"       => $this->finance_van['bank_code'],
            "TRSC_SEQ_NO"   => (string)$this->trsc_no,
        ];
    }

    protected function getRecvParams()
    {
        if($this->is_test)
            $this->profit = 5000;

        return [
            "RCV_BNK_CD"    => $this->privacy['acct_bank_code'],
            "RCV_ACCT_NO"   => $this->privacy['acct_num'],
            "TRSC_AMT"      => $this->profit,
        ];
    }

    protected function getTrxDttm($trx_at)
    {
        $trx_at = str_replace('-', '', $trx_at);
        $trx_at = str_replace(' ', '', $trx_at);
        return str_replace(':', '', $trx_at);
    }

    protected function getAccountAuthAESEncrypt($value)
    {
        $enc_data = base64_encode(
            openssl_encrypt(
                $value,
                'AES-256-CBC',
                $this->finance_van['enc_key'],
                OPENSSL_RAW_DATA,
                str_repeat(chr(0), 16)
            )
        );
        return urlencode(utf8_encode($enc_data));
    }

    protected function getAccountAuthAESDecrypt($value)
    {
        $decode = utf8_encode(urldecode($input));
        return base64_decode(
            openssl_encrypt(
                $decode,
                'AES-256-CBC',
                $this->finance_van['enc_key'],
                OPENSSL_RAW_DATA,
                str_repeat(chr(0), 16)
            )
        );
    }

    protected function getAccountAuthHmacSha256($value)
    {
        $enc_data = base64_encode(
            hash_hmac(
                'sha256',
                $value,
                $this->finance_van['enc_key'],
                true
            )
        );
        return urlencode(utf8_encode($enc_data));
    }

    protected function verifyAccountAuthHmac($value, $hmac)
    {
        $data = $this->getAccountAuthAESDecrypt($value);
        //데이터 복호화 AES256
        $check_hmac = $this->getAccountAuthHmacSha256(substr($data, 14));
        if($hmac === $check_hmac)
            return false;
        else
            return true;
    }

    protected function getBankCode($bank_name)
    {
        $banks = [
            ['code' => '002', 'name' => '산업은행'],
            ['code' => '003', 'name' => '기업은행'],
            ['code' => '004', 'name' => '국민은행'],
            ['code' => '007', 'name' => '수협은행'],
            ['code' => '011', 'name' => '농협은행'],
            ['code' => '012', 'name' => '농협중앙회'],
            ['code' => '020', 'name' => '우리은행'],
            ['code' => '023', 'name' => 'SC제일은행'],
            ['code' => '027', 'name' => '한국씨티은행'],
            ['code' => '031', 'name' => '대구은행'],
            ['code' => '032', 'name' => '부산은행'],
            ['code' => '034', 'name' => '광주은행'],
            ['code' => '035', 'name' => '제주은행'],
            ['code' => '037', 'name' => '전북은행'],
            ['code' => '039', 'name' => '경남은행'],
            ['code' => '045', 'name' => '새마을금고연합회'],
            ['code' => '048', 'name' => '신협중앙회'],
            ['code' => '050', 'name' => '저축은행'],
            ['code' => '052', 'name' => '모건스탠리은행'],
            ['code' => '054', 'name' => 'HSBC은행'],
            ['code' => '055', 'name' => '도이치은행'],
            ['code' => '057', 'name' => '제이피모간체이스은행'],
            ['code' => '058', 'name' => '미즈호코퍼레이트은행'],
            ['code' => '059', 'name' => '엠유에프지은행'],
            ['code' => '060', 'name' => 'BOA'],
            ['code' => '061', 'name' => '비엔피파리바은행'],
            ['code' => '062', 'name' => '중국공상은행'],
            ['code' => '063', 'name' => '중국은행'],
            ['code' => '064', 'name' => '산림조합'],
            ['code' => '065', 'name' => '대화은행'],
            ['code' => '066', 'name' => '교통은행'],
            ['code' => '067', 'name' => '중국건설은행'],
            ['code' => '071', 'name' => '우체국'],
            ['code' => '081', 'name' => '하나은행'],
            ['code' => '088', 'name' => '신한은행'],
            ['code' => '089', 'name' => '케이뱅크'],
            ['code' => '090', 'name' => '카카오뱅크'],
            ['code' => '092', 'name' => '토스뱅크'],
            ['code' => '209', 'name' => '유안타증권'],
            ['code' => '218', 'name' => 'KB증권'],
            ['code' => '238', 'name' => '미래에셋증권'],
            ['code' => '240', 'name' => '삼성증권'],
            ['code' => '243', 'name' => '한국투자증권'],
            ['code' => '247', 'name' => 'NH투자증권'],
            ['code' => '261', 'name' => '교보증권'],
            ['code' => '262', 'name' => '하이투자증권'],
            ['code' => '263', 'name' => '현대차증권'],
            ['code' => '264', 'name' => '키움증권'],
            ['code' => '265', 'name' => '이베스트투자증권'],
            ['code' => '266', 'name' => 'SK증권'],
            ['code' => '267', 'name' => '대신증권'],
            ['code' => '269', 'name' => '한화투자증권'],
            ['code' => '270', 'name' => '하나금융증권'],
            ['code' => '278', 'name' => '신한금융투자'],
            ['code' => '279', 'name' => 'DB금융투자'],
            ['code' => '280', 'name' => '유진투자증권'],
            ['code' => '287', 'name' => '메리츠증권'],
            ['code' => '288', 'name' => '카카오페이증권'],
            ['code' => '290', 'name' => '부국증권'],
            ['code' => '291', 'name' => '신영증권'],
            ['code' => '292', 'name' => '케이프투자증권'],
            ['code' => '293', 'name' => '한국증권금융'],
            ['code' => '294', 'name' => '한국포스증권'],
        ];
        if(strpos($bank_name, '저축은행') !== false)
            return '050';
        else
        {
            $idx = array_search($bank_name, array_column($banks, 'name'));
            return $idx !== false ? $banks[$idx]['code'] : null;
        }
    }

    protected function getAuthErrorInfo($res, $default_message)
    {
        if(isset($res['body']['error_description']))
        {
            return [
                1999,
                $res['body']['error_description']
            ];
        }
        else
        {
            return [
                1999,
                $default_message,
            ];
        }
    }

    protected function getErrorMessage($error_code, $message)
    {
        $errors = [
            ['code' => 'P413', 'message' => '기타오류발생'],
            ['code' => 'P420', 'message' => '거래일자 상이'],
            ['code' => 'P421', 'message' => '당일거래만 가능'],
            ['code' => 'P422', 'message' => '미등록 서비스기관'],
            ['code' => 'P424', 'message' => '서비스기관 상태 확인요망'],
            ['code' => 'P425', 'message' => '송금가능 잔액 부족'],
            ['code' => 'P426', 'message' => '송금계좌번호 상이'],
            ['code' => 'P427', 'message' => '송금금액 상이'],
            ['code' => 'P428', 'message' => '송금금액 오류'],
            ['code' => 'P429', 'message' => '송금서비스 가능 업체 아님'],
            ['code' => 'P429', 'message' => '송금서비스 가능 업체 아님'],
            ['code' => 'P432', 'message' => '송금계좌번호 오류'],
            ['code' => 'P433', 'message' => '송금영업내한도금액 초과'],
            ['code' => 'P434', 'message' => '송금영업외한도금액 초과'],
            ['code' => 'P435', 'message' => '송금영업외한도금액전일합계 초과'],
            ['code' => 'P436', 'message' => '송금은행 상이'],
            ['code' => 'P437', 'message' => '송금은행코드 오류'],
            ['code' => 'P438', 'message' => '잔액부족'],
            ['code' => 'P439', 'message' => '원거래 거래구분 상이. (거래구분<>350)'],
            ['code' => 'P441', 'message' => '원거래 상태 확인요망. 전문버림'],
            ['code' => 'P441', 'message' => '원거래 상태 확인요망'],
            ['code' => 'P443', 'message' => '원거래 송금계좌 상이.'],
            ['code' => 'P444', 'message' => '원거래 송금금액 상이.'],
            ['code' => 'P445', 'message' => '원거래 송금은행코드 상이.'],
            ['code' => 'P446', 'message' => '원거래 입출구분 상이. (입출구분<>2)'],
            ['code' => 'P448', 'message' => '원거래 출금계좌 상이.'],
            ['code' => 'P449', 'message' => '원거래 출금은행코드 상이.'],
            ['code' => 'P450', 'message' => '원거래없음'],
            ['code' => 'P451', 'message' => '은행기관 거래 마감시간 초과'],
            ['code' => 'P452', 'message' => '은행기관 상태 확인요망'],
            ['code' => 'P453', 'message' => '출금계좌번호 상이'],
            ['code' => 'P454', 'message' => '출금계좌번호 오류'],
            ['code' => 'P455', 'message' => '출금은행 오류'],
            ['code' => 'P456', 'message' => '출금은행코드 상이'],
            ['code' => 'P457', 'message' => '휴일한도금액 초과'],
            ['code' => '001', 'message' => '입금의뢰필'],
            ['code' => '033', 'message' => '만료카드, 카드회수'],
            ['code' => '036', 'message' => '분실도난카드, 카드회수'],
            ['code' => '038', 'message' => '비밀번호 입력횟수 초과, 카드회수'],
            ['code' => '054', 'message' => '만료카드'],
            ['code' => '055', 'message' => '비밀번호 상위'],
            ['code' => '059', 'message' => '위.변조 카드'],
            ['code' => '061', 'message' => '지급한도 초과 (1 일 1 회 한도초과)'],
            ['code' => '062', 'message' => '분실도난 카드'],
            ['code' => '065', 'message' => '지급횟수 초과'],
            ['code' => '075', 'message' => '비밀번호 입력횟수 초과'],
            ['code' => '076', 'message' => '해당계좌 없음(전출,해약,잡좌통할 포함)'],
            ['code' => '077', 'message' => 'CMS 계좌 입금 불가'],
            ['code' => '078', 'message' => '출금불가 MSG 등록계좌(개설점 연락)'],
            ['code' => '079', 'message' => '계좌이체 불가계좌(당좌예금, 적금,신탁등)'],
            ['code' => '080', 'message' => '불입금상위(1 회 불입단위가 있는 계좌)'],
            ['code' => '081', 'message' => '어음교환소 코드오류'],
            ['code' => '086', 'message' => '계좌에 관련정보 없음'],
            ['code' => '089', 'message' => '개설은행 장애'],
            ['code' => '091', 'message' => '비서비스은행'],
            ['code' => '092', 'message' => '은행코드 없음 (미참가은행)'],
            ['code' => '099', 'message' => '기타오류발생'],
            ['code' => '0N3', 'message' => '예금잔액 부족'],
            ['code' => '0N4', 'message' => '지급가능잔액 부족 (타점권 미결)'],
            ['code' => '0N5', 'message' => '대월한도 초과 (대월잔액 부족)'],
            ['code' => '0N6', 'message' => '수수료 부족(출금시 총잔액중 차감액 없음)'],
            ['code' => '0N7', 'message' => '연체계좌'],
            ['code' => '0N8', 'message' => '잔액 및 부채증명 발급계좌'],
            ['code' => '0N9', 'message' => '통장정리후 거래 (무통건수 초과)'],
            ['code' => '0NA', 'message' => '통장분실'],
            ['code' => '0NB', 'message' => '인감분실'],
            ['code' => '0NC', 'message' => '카드발급 미등록'],
            ['code' => '0ND', 'message' => '법적등록계좌 (압류,가압류,예금주사망등)'],
            ['code' => '0NE', 'message' => '비밀번호 상위'],
            ['code' => '0NF', 'message' => '유효성코드 갱신요망'],
            ['code' => '0NK', 'message' => '거래정지 회원'],
            ['code' => '0NL', 'message' => '주민등록번호 미등록, 실명계좌 아님'],
            ['code' => '0NM', 'message' => '현금서비스 월간이용한도 초과'],
            ['code' => '0NN', 'message' => '가족회원 미등록회원'],
            ['code' => '0NP', 'message' => '법인카드 현금서비스 불가'],
            ['code' => '0NQ', 'message' => '수취계좌 없음'],
            ['code' => '0NR', 'message' => '수취계좌 예금한도 초과'],
            ['code' => '0NS', 'message' => '기타수취 불가'],
            ['code' => '0NV', 'message' => '해당 계정 마감후 입금불가'],
            ['code' => '100', 'message' => '1 일 사용회수 초과회원'],
            ['code' => '101', 'message' => '1 일 이체가능 건수초과'],
            ['code' => '102', 'message' => '1 일 이체한도 초과'],
            ['code' => '103', 'message' => '일일출금한도초과'],
            ['code' => '104', 'message' => '지급회수초과'],
            ['code' => '105', 'message' => '1 일 한도초과된 회원'],
            ['code' => '106', 'message' => '1 종 사고계좌 (입지정지)'],
            ['code' => '107', 'message' => '잔액증명，부채증명 상태입니다'],
            ['code' => '108', 'message' => '1 종 사고계좌 (적수변경 대상)'],
            ['code' => '109', 'message' => '파산선고된 계좌입니다'],
            ['code' => '110', 'message' => '1 회 1 백억이상 거래 불가'],
            ['code' => '111', 'message' => '1 회 이체가능 금액초과'],
            ['code' => '112', 'message' => '1 회 지급한도 금액초과'],
            ['code' => '113', 'message' => '1 회 지급한도 횟수초과'],
            ['code' => '114', 'message' => '1 회한도를 초과한 타행거래는 정정 불가'],
            ['code' => '115', 'message' => '부도발생 계좌'],
            ['code' => '116', 'message' => '2 종 사고계좌 (거래해지 등록)'],
            ['code' => '117', 'message' => '2 종 사고계좌 (범인사고 등록)'],
            ['code' => '118', 'message' => '2 종 사고계좌 (법적수속)'],
            ['code' => '119', 'message' => '입금계좌 압류상태이므로 입금불가'],
            ['code' => '120', 'message' => '인감분실계좌'],
            ['code' => '121', 'message' => '2 종 사고계좌 (지급정지)'],
            ['code' => '122', 'message' => '통장증서 분실상태임'],
            ['code' => '123', 'message' => '가상 모계좌로 직접 입금안됨'],
            ['code' => '124', 'message' => '가상계좌거래내역생성오류'],
            ['code' => '125', 'message' => '가상계좌 시스템 오류'],
            ['code' => '126', 'message' => '가상계좌일련번호갱신오류'],
            ['code' => '127', 'message' => '가상계좌일련번호산출오류'],
            ['code' => '128', 'message' => '가입자원장상태불량,STATUS=SEGNAMEX,RC'],
            ['code' => '129', 'message' => '가입자등록관리원장상태불량,SEGNAME,RC'],
            ['code' => '130', 'message' => '개별부 불능코드 참조'],
            ['code' => '131', 'message' => '이중거래가 발생되었습니다'],
            ['code' => '132', 'message' => '개설은행 서비스시간 아님'],
            ['code' => '133', 'message' => '개설은행 수신전문 오류'],
            ['code' => '134', 'message' => '개설은행 업무종료'],
            ['code' => '135', 'message' => '개설은행 이체처리중'],
            ['code' => '136', 'message' => '개설기관 장애'],
            ['code' => '137', 'message' => '개설기관 처리중'],
            ['code' => '138', 'message' => '개설기관 코드오류'],
            ['code' => '139', 'message' => '개설은행 SYSTEM 장애'],
            ['code' => '140', 'message' => '개설은행 가계종합 계정 처리불가'],
            ['code' => '141', 'message' => '개설은행 기업자유저축 계정 처리불가'],
            ['code' => '142', 'message' => '개설은행 당좌계정 처리불가'],
            ['code' => '143', 'message' => '개설은행 별단계정 처리불가'],
            ['code' => '144', 'message' => '개설은행 보통계정 처리불가'],
            ['code' => '145', 'message' => '개설은행 신탁계정 처리불가'],
            ['code' => '146', 'message' => '개설은행 자유저축 계정 처리불가'],
            ['code' => '147', 'message' => '개설은행 장애'],
            ['code' => '148', 'message' => '개설은행 저축계정 처리불가'],
            ['code' => '149', 'message' => '개설은행 적금계정 처리불가'],
            ['code' => '150', 'message' => '거래불가능 시간입니다．'],
            ['code' => '151', 'message' => '거래 가능일 아님'],
            ['code' => '152', 'message' => '거래구분코드 오류입니다．'],
            ['code' => '153', 'message' => '거래구분코드 오류'],
            ['code' => '154', 'message' => '거래금액 에러'],
            ['code' => '155', 'message' => '거래금액 오류'],
            ['code' => '156', 'message' => '거래금액 한도 초과'],
            ['code' => '157', 'message' => '다음 거래내역이 없습니다'],
            ['code' => '158', 'message' => '거래 무응답 (대사 자료시)'],
            ['code' => '159', 'message' => '거래중지 계좌'],
            ['code' => '160', 'message' => '거래 불가능 시간'],
            ['code' => '161', 'message' => '거래가 없습니다'],
            ['code' => '162', 'message' => '거래일련번호를 반드시 입력해야 합니다'],
            ['code' => '163', 'message' => '거래 정지'],
            ['code' => '164', 'message' => '거래 종류 에러'],
            ['code' => '165', 'message' => '거래취급금액 상위'],
            ['code' => '166', 'message' => '거래취급번호 오류'],
            ['code' => '167', 'message' => '거래취급일자 상위'],
            ['code' => '168', 'message' => '거래취급점 상위'],
            ['code' => '169', 'message' => '거래코드오류'],
            ['code' => '170', 'message' => '거래한도가 초과 되었습니다'],
            ['code' => '171', 'message' => '거래한도액 오류'],
            ['code' => '172', 'message' => '거래할 수 없는 과목의 계좌입니다'],
            ['code' => '173', 'message' => '거래항목 오류입니다．'],
            ['code' => '174', 'message' => '거래허용 회선이 아닙니다'],
            ['code' => '175', 'message' => '거래일이 당일보다 큽니다'],
            ['code' => '176', 'message' => '거래일자가 당일자가 아닙니다．'],
            ['code' => '177', 'message' => '거래일이 휴일임'],
            ['code' => '178', 'message' => '거래일자 오류'],
            ['code' => '179', 'message' => '거래점과 계좌점이 상이 합니다'],
            ['code' => '180', 'message' => '거래점번호 입력오류'],
            ['code' => '181', 'message' => '거래점 입력오류 입니다'],
            ['code' => '182', 'message' => '건수오류'],
            ['code' => '183', 'message' => '결과코드 입력하세요'],
            ['code' => '184', 'message' => '결번요구시 결번없음'],
            ['code' => '185', 'message' => '결제계좌 오류 입니다'],
            ['code' => '186', 'message' => '결제구분 오류'],
            ['code' => '187', 'message' => '결제원처리중'],
            ['code' => '188', 'message' => '결제원 타행환 종료로 취소가 안됩니다'],
            ['code' => '189', 'message' => '결제원 SYSTEM 이 장애중입니다'],
            ['code' => '190', 'message' => '경고 코드 보유'],
            ['code' => '191', 'message' => '계정과목오류'],
            ['code' => '192', 'message' => '계좌에 관련정보 없음'],
            ['code' => '193', 'message' => '계좌번호 (해지, 미등록)'],
            ['code' => '194', 'message' => '계좌발급중 오류'],
            ['code' => '195', 'message' => '출금계좌 비밀번호 상이'],
            ['code' => '196', 'message' => '현계좌상태 오류입니다'],
            ['code' => '197', 'message' => '계좌오류'],
            ['code' => '198', 'message' => '계좌전출중'],
            ['code' => '199', 'message' => '계좌번호 체계 오류'],
            ['code' => '200', 'message' => '계좌번호 미입력입니다'],
            ['code' => '201', 'message' => '계좌번호변경구분 확인하세요'],
            ['code' => '202', 'message' => '입금계좌번호가 일치하지 않습니다'],
            ['code' => '203', 'message' => '계좌번호오류'],
            ['code' => '204', 'message' => '계좌번호를 입력하지 마세요'],
            ['code' => '205', 'message' => '계좌번호 확인(입금계좌,지급계좌 동일)'],
            ['code' => '206', 'message' => '계좌이체거래불가계좌 당좌예금.적금.신탁'],
            ['code' => '207', 'message' => '계좌이체 할 수 없는 시간입니다'],
            ['code' => '208', 'message' => '계좌이체 서비스를 가입하지 않은 고객'],
            ['code' => '209', 'message' => '고객번호발견안됨．당행으로 확인요망'],
            ['code' => '210', 'message' => '고객원장상태불량,상태=SEGNAMEX,RC'],
            ['code' => '211', 'message' => '고유번호 누락'],
            ['code' => '212', 'message' => '공동망 거래구분 오류입니다'],
            ['code' => '213', 'message' => '공동망업무 종료후 거래 할 수 없습니다'],
            ['code' => '214', 'message' => '공동망업무 종료처리중 입니다'],
            ['code' => '215', 'message' => '과목코드오류'],
            ['code' => '216', 'message' => '과목코드＝은행코드 상위'],
            ['code' => '217', 'message' => '관세납부 이중거래'],
            ['code' => '218', 'message' => '관세납부 입금（국고）계좌오류'],
            ['code' => '219', 'message' => '귀부점 처리불가'],
            ['code' => '220', 'message' => '금액 내역이 일치하지 않습니다'],
            ['code' => '221', 'message' => '금액자리에 문자있음'],
            ['code' => '222', 'message' => '금액 입력하지마세요'],
            ['code' => '223', 'message' => '금액 한도가 초과되었습니다.'],
            ['code' => '224', 'message' => '금융결제원 업무종료 상태'],
            ['code' => '225', 'message' => '금융결제원 장애로 거래가 안됩니다'],
            ['code' => '226', 'message' => '이미 실명 등록된 계좌입니다'],
            ['code' => '227', 'message' => '이미 등록된 번호임'],
            ['code' => '228', 'message' => '이미 불능 처리되었습니다'],
            ['code' => '229', 'message' => '이미 업무개시를 하였습니다'],
            ['code' => '230', 'message' => '이미 정상 처리되었습니다'],
            ['code' => '231', 'message' => '기 조회된 수표임'],
            ['code' => '232', 'message' => '집계전문을 이미수신 했습니다．'],
            ['code' => '233', 'message' => '기처리된 내용과 상이'],
            ['code' => '234', 'message' => '등록된출금계좌가 아닙니다．'],
            ['code' => '235', 'message' => '기 통지전문'],
            ['code' => '236', 'message' => '기 할당계좌번호'],
            ['code' => '237', 'message' => '기관거래가능코드없음'],
            ['code' => '238', 'message' => '기관거래가능코드오류'],
            ['code' => '239', 'message' => '기관수수료청구내역갱신오류'],
            ['code' => '240', 'message' => '기관수수료청구내역생성오류'],
            ['code' => '241', 'message' => '기관수수료청구내역없음'],
            ['code' => '242', 'message' => '기관원장갱신오류'],
            ['code' => '243', 'message' => '기관코드오류'],
            ['code' => '244', 'message' => '기준일이 대출실행일보다 작거나 큽니다'],
            ['code' => '245', 'message' => '기타 거래 불가'],
            ['code' => '246', 'message' => '기타수취불가（해당개설점연락）'],
            ['code' => '247', 'message' => '기타오류 입니다．'],
            ['code' => '248', 'message' => '기타이체 불능'],
            ['code' => '249', 'message' => '기타입출금 불가(계좌없음 or 가상계좌)'],
            ['code' => '250', 'message' => '기한이익상실등록계좌 거래할수없음'],
            ['code' => '251', 'message' => '납부자번호 오류'],
            ['code' => '252', 'message' => '단말소속 틀림'],
            ['code' => '253', 'message' => '단말별 거래정보 저장시 오류'],
            ['code' => '254', 'message' => '당일자 거래가 아직 없습니다'],
            ['code' => '255', 'message' => '당일거래모드만 가능함'],
            ['code' => '256', 'message' => '당일등록건수를 초과했습니다'],
            ['code' => '257', 'message' => '당일자 환율 미고시'],
            ['code' => '258', 'message' => '당일조회는 안됩니다'],
            ['code' => '259', 'message' => '당행에 계약등록후 거래하십시오'],
            ['code' => '260', 'message' => '당행 계좌번호 오류'],
            ['code' => '261', 'message' => '타행환업무가 종료 되었습니다'],
            ['code' => '262', 'message' => '당행장애로 타행이체 불가합니다'],
            ['code' => '263', 'message' => '당행코드 오류입니다．'],
            ['code' => '264', 'message' => '대리점 오류'],
            ['code' => '265', 'message' => '대외 미처리 조회는 처리번호 99 입력해라'],
            ['code' => '266', 'message' => '대외이체거래는 대체금액만 가능'],
            ['code' => '267', 'message' => '대월한도 초과 (대월잔액 부족)'],
            ['code' => '268', 'message' => '대출원장상태불량,상태=SEGNAMEX,RC,AC=XX'],
            ['code' => '269', 'message' => '대출이자 원가된 계좌입니다'],
            ['code' => '270', 'message' => '대출이자 원가후 거래하세요'],
            ['code' => '271', 'message' => '동일계좌로 이체 불가'],
            ['code' => '272', 'message' => '등록구분코드를 정확히 입력하십시오'],
            ['code' => '273', 'message' => '기 취소된 거래임'],
            ['code' => '274', 'message' => '등록사실이 없습니다'],
            ['code' => '275', 'message' => '등록일자를 반드시 입력해야 합니다'],
            ['code' => '276', 'message' => '등록정보 없음'],
            ['code' => '277', 'message' => '로그처리 에러'],
            ['code' => '278', 'message' => '리스료 이체등록 해제후 거래하세요'],
            ['code' => '279', 'message' => '리얼타임 펌뱅킹 미가입 고객입니다'],
            ['code' => '280', 'message' => '리얼타임 펌뱅킹 업무가 이미 신규됨'],
            ['code' => '281', 'message' => '마감후 거래 불가함.'],
            ['code' => '282', 'message' => '마감후 개시불가, 업무재개시를 이용'],
            ['code' => '283', 'message' => '마감후 해지된 계좌입니다'],
            ['code' => '284', 'message' => '만기후 1 년초과계좌 거래가불가능 합니다'],
            ['code' => '285', 'message' => '만료카드'],
            ['code' => '286', 'message' => '매수오류'],
            ['code' => '287', 'message' => '메세지 코드 오류'],
            ['code' => '288', 'message' => '모계좌미등록'],
            ['code' => '289', 'message' => '모계좌잔액부족'],
            ['code' => '290', 'message' => '모업체 등록점에서만 처리 가능합니다'],
            ['code' => '291', 'message' => '무거래 (수표부도 사유)'],
            ['code' => '292', 'message' => '무통장 건수가 초과되었습니다'],
            ['code' => '293', 'message' => '미기장정리후 거래하세요'],
            ['code' => '294', 'message' => '미등록된 계좌(입금계좌)'],
            ['code' => '295', 'message' => '미등록계좌가 없습니다'],
            ['code' => '296', 'message' => '미발행 수표임'],
            ['code' => '297', 'message' => '미참가 이용기관코드'],
            ['code' => '298', 'message' => '발급내역 없음'],
            ['code' => '299', 'message' => '발급해제'],
            ['code' => '300', 'message' => '발행인 입력하십시요'],
            ['code' => '301', 'message' => '발행일자는 반드시 입력해야합니다'],
            ['code' => '302', 'message' => '버스카드 번호 오류'],
            ['code' => '303', 'message' => '주의=> 범죄관련계좌'],
            ['code' => '304', 'message' => '법적제한계좌'],
            ['code' => '305', 'message' => '변경내용이 없습니다'],
            ['code' => '306', 'message' => '변조. 위조 (수표부도 사유)'],
            ['code' => '307', 'message' => '해당전문 복기암호부호가 틀림.확인 요망'],
            ['code' => '308', 'message' => '복기부호 오류'],
            ['code' => '309', 'message' => '본 회선으로는 서비스 되지 않습니다'],
            ['code' => '310', 'message' => '본부 장애 잠시후 거래하세요'],
            ['code' => '311', 'message' => '본부 처리중 잠시후 다시 거래하세요'],
            ['code' => '312', 'message' => '본인 사망한 계좌입니다'],
            ['code' => '313', 'message' => '부도연장금액과 입금타점액 다릅니다'],
            ['code' => '314', 'message' => '부도연장금액액이 있어 거래할수없음'],
            ['code' => '315', 'message' => '부도일자 확인하세요'],
            ['code' => '316', 'message' => '부도지급액이 부도연장금액보다 큽니다'],
            ['code' => '317', 'message' => '분실도난카드'],
            ['code' => '318', 'message' => '불입횟수 초과(해당 개설점 연락)'],
            ['code' => '319', 'message' => '비고코드 확인하세요'],
            ['code' => '320', 'message' => '통장 비밀번호가 틀립니다. 확인 요망'],
            ['code' => '321', 'message' => '비밀번호오류'],
            ['code' => '322', 'message' => '비밀오류회수초과'],
            ['code' => '323', 'message' => '주민등록번호 미등록, 실명계좌 아님'],
            ['code' => '324', 'message' => '비자카드 결제계좌'],
            ['code' => '325', 'message' => '사고등록이안된계좌'],
            ['code' => '326', 'message' => '주의사고정보 등록'],
            ['code' => '327', 'message' => '사망，실종，파산고객입니다．'],
            ['code' => '328', 'message' => '상대은행 계좌오류 없음'],
            ['code' => '329', 'message' => '상대은행（입금은행）장애상태 입니다.'],
            ['code' => '330', 'message' => '상대은행 코드 오류'],
            ['code' => '331', 'message' => '상대점 마감'],
            ['code' => '332', 'message' => '상환기일 경과하여 선납할 수 없습니다'],
            ['code' => '333', 'message' => '해당서비스 안함'],
            ['code' => '334', 'message' => '서비스 종료'],
            ['code' => '335', 'message' => '센터 입금처리 중입니다'],
            ['code' => '336', 'message' => '센터 장애'],
            ['code' => '337', 'message' => '센터 처리중 잠시후 확인하세요'],
            ['code' => '338', 'message' => '센터 BUSY'],
            ['code' => '339', 'message' => '송신자명 오류'],
            ['code' => '340', 'message' => '송신자암호 오류'],
            ['code' => '341', 'message' => '수수료 계산시 오류(POBXG04)'],
            ['code' => '342', 'message' => '수수료 금액 오류'],
            ['code' => '343', 'message' => '수수료부족(출금시총잔액중차감액없음)'],
            ['code' => '344', 'message' => '해당계좌없음'],
            ['code' => '345', 'message' => '수취인계좌 잔액증명서발부'],
            ['code' => '346', 'message' => '수취인계좌 통장입금건수 초과'],
            ['code' => '347', 'message' => '수취인 성명 없음'],
            ['code' => '348', 'message' => '수취인성명 오류'],
            ['code' => '349', 'message' => '수취인 성명 코드 오류'],
            ['code' => '350', 'message' => '수취인 성명조회 거래시간 아님'],
            ['code' => '351', 'message' => '수취인 성명조회 거래일자 틀림'],
            ['code' => '352', 'message' => '수취인 성명조회 계좌 오류'],
            ['code' => '353', 'message' => '수취인 성명조회 계좌번호 발견안됨'],
            ['code' => '354', 'message' => '수취인 성명조회 교환소 없음'],
            ['code' => '355', 'message' => '수취인 성명조회 업무폭주. 잠시후하세요'],
            ['code' => '356', 'message' => '수취인 성명조회 원거래 불명'],
            ['code' => '357', 'message' => '수취인 성명조회 은행으로 연락바람'],
            ['code' => '358', 'message' => '수취인 성명조회 은행코드 오류'],
            ['code' => '359', 'message' => '수취인 성명조회 타은행 장애'],
            ['code' => '360', 'message' => '수취인 성명조회 휴일 거래안됨'],
            ['code' => '361', 'message' => '수취인 성명조회 Line Stop'],
            ['code' => '362', 'message' => '수취인계좌 입금한도 초과'],
            ['code' => '363', 'message' => '수취인 통장정리후 거래가능'],
            ['code' => '364', 'message' => '수표구분 코드 상이'],
            ['code' => '365', 'message' => '수표금액 상이'],
            ['code' => '366', 'message' => '수표번호 상이'],
            ['code' => '367', 'message' => '순채무한도 초과'],
            ['code' => '368', 'message' => '전문번호숫자아님'],
            ['code' => '369', 'message' => '신규취소계좌로 거래불가．'],
            ['code' => '370', 'message' => '신용불량거래자는 거래할 수 없습니다'],
            ['code' => '371', 'message' => '신청해제일자 당일보다 큽니다'],
            ['code' => '372', 'message' => '신탁원장상태불량,상태=SEGNAMEX,RC,AC=XX'],
            ['code' => '373', 'message' => '신한은행 장애중입니다'],
            ['code' => '374', 'message' => '실명확인후 거래하시요'],
            ['code' => '375', 'message' => '실명번호 오류'],
            ['code' => '376', 'message' => '예금 부족 (수표부도 사유)'],
            ['code' => '377', 'message' => '안내서 미착 (수표부도 사유)'],
            ['code' => '378', 'message' => '어음 교환소 코드 오류'],
            ['code' => '379', 'message' => '어음,수표등이 미결제-지급가능금액 부족'],
            ['code' => '380', 'message' => '업무구분 코드 입력오류입니다'],
            ['code' => '381', 'message' => '업무마감처리불가'],
            ['code' => '382', 'message' => '업무 미개시'],
            ['code' => '383', 'message' => '업무종료'],
            ['code' => '384', 'message' => '업무종료 준비'],
            ['code' => '385', 'message' => '업무중단'],
            ['code' => '386', 'message' => '업체정보 미등록상태입니다．'],
            ['code' => '387', 'message' => '연체계좌'],
            ['code' => '388', 'message' => '연체중 자동(센터)지급 금지고객'],
            ['code' => '389', 'message' => '현재 연체중이므로 거래를 할수 없음'],
            ['code' => '390', 'message' => '원거래가 송금거래 아님'],
            ['code' => '391', 'message' => '원거래 계좌번호 상이'],
            ['code' => '392', 'message' => '원거래 금액 상이'],
            ['code' => '393', 'message' => '원거래 금액을 초과하였습니다'],
            ['code' => '394', 'message' => '원거래 상위'],
            ['code' => '395', 'message' => '원거래 없음(취소시)'],
            ['code' => '396', 'message' => '원거래 이상'],
            ['code' => '397', 'message' => '원거래 입금불능됨'],
            ['code' => '398', 'message' => '원거래 전문관리 번호 상이'],
            ['code' => '399', 'message' => '원거래 취급일자 상이'],
            ['code' => '400', 'message' => '원거래 취소 불가능'],
            ['code' => '401', 'message' => '원장의 고객번호와 일치하지 않습니다'],
            ['code' => '402', 'message' => '원장내에 변경할 지급계좌가 없습니다'],
            ['code' => '403', 'message' => '원장미등록,지급계좌불가'],
            ['code' => '404', 'message' => '원장 발견안됨.당행으로 확인요망'],
            ['code' => '405', 'message' => '원장변경후 거래하세요'],
            ['code' => '406', 'message' => '원장상태오류입니다'],
            ['code' => '407', 'message' => '원장의 지급거래번호가 오류입니다'],
            ['code' => '408', 'message' => '월지급한도 초과'],
            ['code' => '409', 'message' => '유동성 계좌만 가능 합니다'],
            ['code' => '410', 'message' => '유효기한이 경과한 카드입니다'],
            ['code' => '411', 'message' => '은행센타의 타행환취급개시이전'],
            ['code' => '412', 'message' => '은행시간초과 , 잠시 후 조회하세요'],
            ['code' => '413', 'message' => '은행에 입금계좌로 등록된계좌 아님．'],
            ['code' => '414', 'message' => '은행 처리중 오류'],
            ['code' => '415', 'message' => '은행코드 오류입니다'],
            ['code' => '416', 'message' => '은행코드를 정확히 입력하십시오'],
            ['code' => '417', 'message' => '응답전문 거래코드 오류입니다'],
            ['code' => '418', 'message' => '응답전문 오류입니다'],
            ['code' => '419', 'message' => '응답전문 은행코드 오류입니다'],
            ['code' => '420', 'message' => '응답전문이 상위합니다'],
            ['code' => '421', 'message' => '의뢰인번호를 확인하세요'],
            ['code' => '422', 'message' => '의뢰인 성명 없음'],
            ['code' => '423', 'message' => '의뢰인 성명 코드 오류'],
            ['code' => '424', 'message' => '이관좌'],
            ['code' => '425', 'message' => '이관해지된 계좌입니다'],
            ['code' => '426', 'message' => '이용가능 거래회수 초과입니다'],
            ['code' => '427', 'message' => '이용가능로 등록된 기관이 아닙니다．'],
            ['code' => '428', 'message' => '이용기관 식별코드 오류입니다．'],
            ['code' => '429', 'message' => '이자납입종료일이 상환일을 초과'],
            ['code' => '430', 'message' => '이자납입종료일이 원장이자납입종료일이전'],
            ['code' => '431', 'message' => '이자액과 정정금액이 일치하지 않습니다'],
            ['code' => '432', 'message' => '이자조회필 계좌, 계좌점에 문의요망'],
            ['code' => '433', 'message' => '이자지급후 거래하시오'],
            ['code' => '434', 'message' => '이자가 선취되어 있습니다'],
            ['code' => '435', 'message' => '업무개시전문 수신전 입니다．'],
            ['code' => '436', 'message' => '타행환미개시'],
            ['code' => '437', 'message' => '이체 가능시간이 아직 안되었읍니다'],
            ['code' => '438', 'message' => '이체거래내역 작성이 불가능합니다'],
            ['code' => '439', 'message' => '이체 건수 오류'],
            ['code' => '440', 'message' => '일간 한도가 초과된 회원 입니다'],
            ['code' => '441', 'message' => '이체금액을 입력해주십시요'],
            ['code' => '442', 'message' => '이체금액이 0 원입니다 확인하신후 입력'],
            ['code' => '443', 'message' => '이체금액한도 초과'],
            ['code' => '444', 'message' => '이체일자가 오류입니다．'],
            ['code' => '445', 'message' => '이체 입금대상예금이 아닙니다'],
            ['code' => '446', 'message' => '이체 지급대상예금이 아닙니다'],
            ['code' => '447', 'message' => '인감서명 상이 (수표부도 사유)'],
            ['code' => '448', 'message' => '인출가능금액 계산에서 오류발생'],
            ['code' => '449', 'message' => '일련번호에 동일한 분할번호가 있습니다.'],
            ['code' => '450', 'message' => '일부금액불능(거래조회시)'],
            ['code' => '451', 'message' => '일자를 정확히 입력해주십시오'],
            ['code' => '452', 'message' => '일자를 확인하세요'],
            ['code' => '453', 'message' => '일자오류 입니다．'],
            ['code' => '454', 'message' => '입금거래가 불가능'],
            ['code' => '455', 'message' => '입금거래가 없습니다'],
            ['code' => '456', 'message' => '입금거래는 처리번호 입력하지 마세요'],
            ['code' => '457', 'message' => '입금계좌번호가 일치하지 않습니다'],
            ['code' => '458', 'message' => '입금계좌점 업무중단'],
            ['code' => '459', 'message' => '입금구분 입력 오류입니다'],
            ['code' => '460', 'message' => '입금금액 확인하세요'],
            ['code' => '461', 'message' => '입금이 불가능한 계좌입니다'],
            ['code' => '462', 'message' => '입금거래가 불가능'],
            ['code' => '463', 'message' => '입금액이 큽니다'],
            ['code' => '464', 'message' => '입금의뢰인란은 금융기관만 입력가능'],
            ['code' => '465', 'message' => '입금접수통보 미수신'],
            ['code' => '466', 'message' => '입금 정지등록 계좌입니다'],
            ['code' => '467', 'message' => '입금,지급계좌가 동일한 거래는 안됩니다'],
            ['code' => '468', 'message' => '입금.지급 정지계좌로 거래할 수 없습니다'],
            ['code' => '469', 'message' => '입금 처리번호 확인하세요'],
            ['code' => '470', 'message' => '입금처리오류로 취소처리가 안됩니다'],
            ['code' => '471', 'message' => '입금처리중'],
            ['code' => '472', 'message' => '입금계좌 개설점에 확인요'],
            ['code' => '473', 'message' => '입금계좌가 거래제한된 상태입니다．'],
            ['code' => '474', 'message' => '입금이 불가능한 계좌입니다'],
            ['code' => '475', 'message' => '입금계좌의 고객번호가 일치하지 않습니다'],
            ['code' => '476', 'message' => '입금계좌의 과목오류 입니다 다시 확인'],
            ['code' => '477', 'message' => '입금계좌 금일 잔액증명 발급 입금불가'],
            ['code' => '478', 'message' => '입금계좌가 당행에 등록되지 않았읍니다'],
            ['code' => '479', 'message' => '입금계좌 로그 처리 에러'],
            ['code' => '480', 'message' => '입금계좌가 당행에 등록되지 않았읍니다'],
            ['code' => '481', 'message' => '입금계좌미지정상태 추가, 해지가 불가'],
            ['code' => '482', 'message' => '입금계좌번호가 발견되지 않았습니다'],
            ['code' => '483', 'message' => '입금계좌번호를 입력해주십시요'],
            ['code' => '484', 'message' => '입금계좌 사고신고로 입금불가'],
            ['code' => '485', 'message' => '입금계좌 오류'],
            ['code' => '486', 'message' => '입금계좌 원장상태불량(당행연락요)'],
            ['code' => '487', 'message' => '입금계좌가 잡좌로 지정된계좌입니다．'],
            ['code' => '488', 'message' => '입금계좌가 타행계좌가 아닙니다'],
            ['code' => '489', 'message' => '입금계좌 한도초과 입금불가능함'],
            ['code' => '490', 'message' => '입금계좌 해지상태임'],
            ['code' => '491', 'message' => '입금은행 개시이전'],
            ['code' => '492', 'message' => '입금은행이 장애입니다'],
            ['code' => '493', 'message' => '입금은행코드를 정확히 입력하십시요'],
            ['code' => '494', 'message' => '입금은행과 CD 공동이용 불가합니다'],
            ['code' => '495', 'message' => '입금인성명 오류 (특수문자)'],
            ['code' => '496', 'message' => '입력식별코드 틀림'],
            ['code' => '497', 'message' => '입력일자가 영업일이 아닙니다'],
            ['code' => '498', 'message' => '입력항목 오류 입니다．'],
            ['code' => '499', 'message' => '입출내역생성오류'],
            ['code' => '500', 'message' => '입출내역원장오류'],
            ['code' => '501', 'message' => '자금이체 관련된 거래가 없읍니다'],
            ['code' => '502', 'message' => '자금이체업무 마감'],
            ['code' => '503', 'message' => '자금화가 되지 않았습니다'],
            ['code' => '504', 'message' => '자동이체미등록'],
            ['code' => '505', 'message' => '출금계좌 잔액부족'],
            ['code' => '506', 'message' => '잔액부족으로 대출발생하여 지급불가능함'],
            ['code' => '507', 'message' => '현재 타행이체가 안됨 잠시후 사용하세요'],
            ['code' => '508', 'message' => '장당최고발행한도초과(수표부도사유)'],
            ['code' => '509', 'message' => '재거래 요망 (개설기관 Busy)'],
            ['code' => '510', 'message' => '한도금액 초과'],
            ['code' => '511', 'message' => '적색，불량거래처입니다．'],
            ['code' => '512', 'message' => '전문결번 요구．'],
            ['code' => '513', 'message' => '전문 길이 에러'],
            ['code' => '514', 'message' => '전문코드 업무구분 오류'],
            ['code' => '515', 'message' => '전문 FORMAT ERROR'],
            ['code' => '516', 'message' => '전문 ID ERROR'],
            ['code' => '517', 'message' => '전문번호 결번발생'],
            ['code' => '518', 'message' => '전문번호 오류'],
            ['code' => '519', 'message' => '전문번호 중복'],
            ['code' => '520', 'message' => '통장기장후 사용요'],
            ['code' => '521', 'message' => '전자금융공동망 장애'],
            ['code' => '522', 'message' => '전자어음 관리번호 오류'],
            ['code' => '523', 'message' => '전자어음번호 오류(10 자리)'],
            ['code' => '524', 'message' => '전체불능(거래조회시)'],
            ['code' => '525', 'message' => '전출입되 계좌입니다．'],
            ['code' => '526', 'message' => '전출입취소된계좌로 거래불가상태입니다'],
            ['code' => '527', 'message' => '점내 전입된 계좌임'],
            ['code' => '528', 'message' => '제공 시간이 아닙니다'],
            ['code' => '529', 'message' => '제시시간 경과 (수표부도 사유)'],
            ['code' => '530', 'message' => '조작자 등록되어 있음'],
            ['code' => '531', 'message' => '조회가능일자가 당일자가 아닙니다.'],
            ['code' => '532', 'message' => '조회가능한 접속통신망이 아닙니다.'],
            ['code' => '533', 'message' => '조회개시일이 조회종료일보다 큽니다'],
            ['code' => '534', 'message' => '조회 거래 불가 잠시후 거래하세요'],
            ['code' => '535', 'message' => '조회구분 코드 오류입니다'],
            ['code' => '536', 'message' => '조회대상기간중 해당내용이 없읍니다'],
            ['code' => '537', 'message' => '조회 대상 거래가 아닙니다'],
            ['code' => '538', 'message' => '조회대상기간중 해당내용이 없읍니다'],
            ['code' => '539', 'message' => '조회하실 수 없는 계좌입니다'],
            ['code' => '540', 'message' => '현재 조회 불가능한 구분코드 입니다'],
            ['code' => '541', 'message' => '조회일이 오늘 날짜보다 큽니다'],
            ['code' => '542', 'message' => '조회점번호 확인하세요'],
            ['code' => '543', 'message' => '종료 연장요구'],
            ['code' => '544', 'message' => '주민번호 오류'],
            ['code' => '545', 'message' => '주소ＤＢ상태불량,STATUS=SEGNAMEX,RC'],
            ['code' => '546', 'message' => '준비계좌입니다'],
            ['code' => '547', 'message' => '중계센터 System 미개시'],
            ['code' => '548', 'message' => '중계서버 TIME-OUT'],
            ['code' => '549', 'message' => '중계센터장애로 취소처리가 안됩니다'],
            ['code' => '550', 'message' => '중계센터 타행환종료'],
            ['code' => '551', 'message' => '중계센턴에서 입금은행으로 입금처리중'],
            ['code' => '552', 'message' => '중계센터 종료'],
            ['code' => '553', 'message' => '전문번호 없음'],
            ['code' => '554', 'message' => '중계센터 데이타베이스장애'],
            ['code' => '555', 'message' => '은행시스템에러'],
            ['code' => '556', 'message' => '증권회사 계좌로는 타점권을 입금불가'],
            ['code' => '557', 'message' => '해당기관 서비스종료'],
            ['code' => '558', 'message' => '증서 재발행번호가 일치하지않습니다'],
            ['code' => '559', 'message' => '지금은 거래량이 많으므로 잠시후에 이용'],
            ['code' => '560', 'message' => '지금금액 오류'],
            ['code' => '561', 'message' => '지금은 서비스 되지않는 지급계좌 입니다'],
            ['code' => '562', 'message' => '지급금액을 확인하세요'],
            ['code' => '563', 'message' => '지급및 해제 제한등록된 계좌입니다'],
            ['code' => '564', 'message' => '지급 방법, 적요, 회차 확인'],
            ['code' => '565', 'message' => '지급은 해지된 업무입니다'],
            ['code' => '566', 'message' => '지급지 상이 (수표부도 사유)'],
            ['code' => '567', 'message' => '지급필 수표임'],
            ['code' => '568', 'message' => '지급회수 초과'],
            ['code' => '569', 'message' => '지급계좌 거래중 잔액변경(재확인)'],
            ['code' => '570', 'message' => '지급계좌 거래중지상태임'],
            ['code' => '571', 'message' => '지급계좌 금일 잔액증명 발급 입금불가'],
            ['code' => '572', 'message' => '지급계좌가 당행에 등록되지 않았읍니다'],
            ['code' => '573', 'message' => '지급계좌 로그 처리 에러'],
            ['code' => '574', 'message' => '지급계좌 발견안됨'],
            ['code' => '575', 'message' => '지급계좌 번호 오류입니다'],
            ['code' => '576', 'message' => '지급계좌번호는 동일한 고객이어야 합니다'],
            ['code' => '577', 'message' => '지급계좌번호를 입력해주십시요'],
            ['code' => '578', 'message' => '지급계좌 변환 오류'],
            ['code' => '579', 'message' => '지급계좌 사고신고상태입니다'],
            ['code' => '580', 'message' => '지급계좌 연체상태임'],
            ['code' => '581', 'message' => '지급계좌 원장상태불량(당행연락요)'],
            ['code' => '582', 'message' => '지급계좌와 입금계좌가 동일합니다.'],
            ['code' => '583', 'message' => '지급계좌점 업무중단'],
            ['code' => '584', 'message' => '지급계좌 지급정지 계좌입니다'],
            ['code' => '585', 'message' => '지급계좌타점권 미결제로 지급가능액부족'],
            ['code' => '586', 'message' => '지점수수료청구내역갱신오류'],
            ['code' => '587', 'message' => '지점수수료청구내역없음'],
            ['code' => '588', 'message' => '지점조회 불가능한 조회구분 입니다'],
            ['code' => '589', 'message' => '지점코드 오류'],
            ['code' => '590', 'message' => '집계내용 상이'],
            ['code' => '591', 'message' => '집계원장갱신오류'],
            ['code' => '592', 'message' => '집계전문 기수신'],
            ['code' => '593', 'message' => '집계정보오류'],
            ['code' => '594', 'message' => '집금번호 누락'],
            ['code' => '595', 'message' => '집금계좌로 펌뱅킹으로 입금 불가'],
            ['code' => '596', 'message' => '참가은행 아님'],
            ['code' => '597', 'message' => '채널 장애'],
            ['code' => '598', 'message' => '처리지연 잠시후 거래바람'],
            ['code' => '599', 'message' => '처리일자 오류'],
            ['code' => '600', 'message' => '처리지연 잠시후 거래바람'],
            ['code' => '601', 'message' => '처리결과조회는 은행코드 입력하지 마세요'],
            ['code' => '602', 'message' => '체신부(우체국) 는 타행환 타점입금'],
            ['code' => '603', 'message' => '총금액과 현금 대체 타점의 합계가 틀림'],
            ['code' => '604', 'message' => '총금액 상이'],
            ['code' => '605', 'message' => '최종거래일 이전일자로 거래할 수 없음'],
            ['code' => '606', 'message' => '최종거래일이 당일보다 큽니다'],
            ['code' => '607', 'message' => '최총처리 전문 번호 불일치 입니다'],
            ['code' => '608', 'message' => '추심대전 수수료 상이'],
            ['code' => '609', 'message' => '출금취소중(무응답, FORMAT ERROR)'],
            ['code' => '610', 'message' => '출금계좌 개설점에 확인요'],
            ['code' => '611', 'message' => '출금계좌비밀번호 미등록 상태입니다．'],
            ['code' => '612', 'message' => '출금계좌번호 오류입니다．'],
            ['code' => '613', 'message' => '출금계좌의 거래 제한된 상태입니다．'],
            ['code' => '614', 'message' => '출금계좌 미등록 상태임'],
            ['code' => '615', 'message' => '출금계좌 비밀번호 상이'],
            ['code' => '616', 'message' => '출금계좌 잔액부족'],
            ['code' => '617', 'message' => '출금불가 Message 등록계좌(개설점연락)'],
            ['code' => '618', 'message' => '출금은행 개시이전'],
            ['code' => '619', 'message' => '출금은행 장애'],
            ['code' => '620', 'message' => '출력 DB 상태불량,STATUS=SEGNAMEX,RC'],
            ['code' => '621', 'message' => '취급할수 없는 거래'],
            ['code' => '622', 'message' => '취급기관 미개시'],
            ['code' => '623', 'message' => '취급은행 업무종료'],
            ['code' => '624', 'message' => '취급기관 코드 오류'],
            ['code' => '625', 'message' => '취급은행 SYSTEM 장애'],
            ['code' => '626', 'message' => '취소는 책임자키 사용'],
            ['code' => '627', 'message' => '취소 대상거래 아님'],
            ['code' => '628', 'message' => '취소불가'],
            ['code' => '629', 'message' => '취소처리됨'],
            ['code' => '630', 'message' => '카드 지급 정지'],
            ['code' => '631', 'message' => '카드회수 (분실도난을제외한사고카드)'],
            ['code' => '632', 'message' => '타인의 계좌로는 거래가 불가능 합니다'],
            ['code' => '633', 'message' => '타점권 입금 불가'],
            ['code' => '634', 'message' => '타행 계좌 에러'],
            ['code' => '635', 'message' => '타행계좌 통장정리후 거래가능'],
            ['code' => '636', 'message' => '타행 계좌과목 오류입니다'],
            ['code' => '637', 'message' => '타행계좌번호 오류'],
            ['code' => '638', 'message' => '타행계좌체계 오류(POBXU00),RC'],
            ['code' => '639', 'message' => '타행 교환소 코드 미등록 지점입니다'],
            ['code' => '640', 'message' => '타행납부자 자동이체등록 해제후 거래'],
            ['code' => '641', 'message' => '타행 법적 제한계좌'],
            ['code' => '642', 'message' => '타행송금대상 거래 아님'],
            ['code' => '643', 'message' => '타행-수수료 = 0'],
            ['code' => '644', 'message' => '타행-수수료구분 = 0'],
            ['code' => '645', 'message' => '타행-수신처리결과 = 0'],
            ['code' => '646', 'message' => '타행수신처리결과 오류입니다'],
            ['code' => '647', 'message' => '타행 수취인계좌 없음'],
            ['code' => '648', 'message' => '타행 수취인계좌 입금한도 초과'],
            ['code' => '649', 'message' => '타행 수취인계좌 잔액증명서 발부'],
            ['code' => '650', 'message' => '타행 수취인 성명 오류'],
            ['code' => '651', 'message' => '타행 이관계좌'],
            ['code' => '652', 'message' => '타행이체 안됨'],
            ['code' => '653', 'message' => '타행이체 개설은행 처리중'],
            ['code' => '654', 'message' => '타행이체건수 불일치'],
            ['code' => '655', 'message' => '타행이체가 정상처리 되지 않았습니다'],
            ['code' => '656', 'message' => '타행이체 중계센터 처리중'],
            ['code' => '657', 'message' => '타행이체 처리중(확인불가)'],
            ['code' => '658', 'message' => '타행입금 불능되어 원거래를 취소합니다.'],
            ['code' => '659', 'message' => '타행입금 처리중 취소거래가 안됩니다'],
            ['code' => '660', 'message' => '타행입금 한도를 넘었습니다.(당행한도)'],
            ['code' => '661', 'message' => '타행자점코드 미등록'],
            ['code' => '662', 'message' => '타행 잡좌계좌'],
            ['code' => '663', 'message' => '타행전산시스템 장애'],
            ['code' => '664', 'message' => '타행 지점코드 오류입니다'],
            ['code' => '665', 'message' => '타행 총금액 상위'],
            ['code' => '666', 'message' => '타행 통장분실 재발행 계좌'],
            ['code' => '667', 'message' => '타행 해당개설점 기타수취불가'],
            ['code' => '668', 'message' => '타행 해당지점 처리불가'],
            ['code' => '669', 'message' => '타행 해약계좌'],
            ['code' => '670', 'message' => '타행이체가 안됨 잠시후 사용하세요'],
            ['code' => '671', 'message' => '타행한 취급거래가 미완료된 상태입니다'],
            ['code' => '672', 'message' => '타행환 입금거래 불가상태입니다．'],
            ['code' => '673', 'message' => '타행환 입금한도 초과입니다．'],
            ['code' => '674', 'message' => '타행환 개시일과 거래일이 틀려 거래 안됨'],
            ['code' => '675', 'message' => '타행환 거래 불가 잠시후 거래하세요'],
            ['code' => '676', 'message' => '현재 타행환 거래 CLOSE 상태'],
            ['code' => '677', 'message' => '현재 타행환 거래 OPEN 상태(조회)'],
            ['code' => '678', 'message' => '타행환 거래불가 계좌'],
            ['code' => '679', 'message' => '현재 타행환 거레 CLOSE 상태(조회)'],
            ['code' => '680', 'message' => '현재 타행환 거레 OPEN 상태'],
            ['code' => '681', 'message' => '타행환 계좌 오류(기타)'],
            ['code' => '682', 'message' => '타행환공동망 업무종료 준비'],
            ['code' => '683', 'message' => '타행환공동망 이체한도를 초과하였습니다'],
            ['code' => '684', 'message' => '타행환공동망이 거래안되는 은행입니다'],
            ['code' => '685', 'message' => '타행환업무 개시전상태입니다．'],
            ['code' => '686', 'message' => '타행환 미처리는 업무종료 후에 확인하세요'],
            ['code' => '687', 'message' => '타행환 업무 중단'],
            ['code' => '688', 'message' => '타행환이체시지급계좌는신청점계좌에한함'],
            ['code' => '689', 'message' => '타행환입금 거래불가'],
            ['code' => '690', 'message' => '현재 타행환 입금, 정정거래 안됩니다'],
            ['code' => '691', 'message' => '타행환입금한도 초과'],
            ['code' => '692', 'message' => '타행환 장애조회 오류입니다'],
            ['code' => '693', 'message' => '타행환전문오류 XXXX=FILEDNAME(XXXXXXXX)'],
            ['code' => '694', 'message' => '타행환 정보 TABLE 오류'],
            ['code' => '695', 'message' => '타행환 조회거래가 안됩니다'],
            ['code' => '696', 'message' => '타행환업무가 종료 되었습니다'],
            ['code' => '697', 'message' => '타행환 종료처리 중입니다'],
            ['code' => '698', 'message' => '타행환 중계센타 장애'],
            ['code' => '699', 'message' => '타행환 참가은행 아님'],
            ['code' => '700', 'message' => '타행환 취급거래가 처리오류된 거래입니다'],
            ['code' => '701', 'message' => '타행환 취소거래가 미완료된 상태입니다'],
            ['code' => '702', 'message' => '타행환 현재 장애 없습니다'],
            ['code' => '703', 'message' => '타행환 현재 장애은행(국민,외환..)'],
            ['code' => '704', 'message' => '통장 계좌번호가 해약된 계좌임.'],
            ['code' => '705', 'message' => '통장 기장후 거래하세요'],
            ['code' => '706', 'message' => '통장재발행 계좌'],
            ['code' => '707', 'message' => '통장정리후거래'],
            ['code' => '708', 'message' => '투입항목 오류'],
            ['code' => '709', 'message' => '특수조건 설정계좌임'],
            ['code' => '710', 'message' => '폐쇄점 계좌 거래불가'],
            ['code' => '711', 'message' => '폐쇄점계좌 없음'],
            ['code' => '712', 'message' => '할당중 오류'],
            ['code' => '713', 'message' => '해당내용 없음'],
            ['code' => '714', 'message' => '해당 거래 타점권 없음'],
            ['code' => '715', 'message' => '해당 건수가 없습니다'],
            ['code' => '716', 'message' => '해당계좌없음'],
            ['code' => '717', 'message' => '해당계좌 전일거래 미종료 잠시후이용'],
            ['code' => '718', 'message' => '해당계좌 발급불가'],
            ['code' => '719', 'message' => '해당계좌가 없거나 계좌상태 오류입니다'],
            ['code' => '720', 'message' => '해당계좌는 조회 할 수 없습니다'],
            ['code' => '721', 'message' => '해당 계좌에 거래가 없습니다'],
            ['code' => '722', 'message' => '해당 고객번호 조회후 입력 하세요'],
            ['code' => '723', 'message' => '해당과목.점 계좌발급불가'],
            ['code' => '724', 'message' => '해당기관수수료율미등록'],
            ['code' => '725', 'message' => '해당기관수수료율오류'],
            ['code' => '726', 'message' => '해당기관없음'],
            ['code' => '727', 'message' => '해당대리점 없음'],
            ['code' => '728', 'message' => '해당서비스 적용해지상태입니다．'],
            ['code' => '729', 'message' => '해당 어음 내역 없음'],
            ['code' => '730', 'message' => '해당업체코드 없음'],
            ['code' => '731', 'message' => '해당원장없음'],
            ['code' => '732', 'message' => '해당은행 가계종합계정 처리불가'],
            ['code' => '733', 'message' => '해당은행 개시이전'],
            ['code' => '734', 'message' => '해당은행 기업자유계정 처리불가'],
            ['code' => '735', 'message' => '해당은행 당좌계정 처리불가'],
            ['code' => '736', 'message' => '해당은행에서 응답이 없습니다'],
            ['code' => '737', 'message' => '해당은행 별단계정 처리불가'],
            ['code' => '738', 'message' => '해당은행 보통계정 처리불가'],
            ['code' => '739', 'message' => '해당은행 시스템 다운'],
            ['code' => '740', 'message' => '해당은행 자유저축계정 처리불가'],
            ['code' => '741', 'message' => '해당은행 장애'],
            ['code' => '742', 'message' => '해당은행 저축계정 처리불가'],
            ['code' => '743', 'message' => '해당 은행 폐쇄'],
            ['code' => '744', 'message' => '해당은행에서 처리중 입니다'],
            ['code' => '745', 'message' => '해당은행의 거래금액이 없습니다'],
            ['code' => '746', 'message' => '해당은행의 비밀번호가 틀립니다'],
            ['code' => '747', 'message' => '해당일자 거래내역없읍니다'],
            ['code' => '748', 'message' => '해당일자 건수,금액이 없습니다'],
            ['code' => '749', 'message' => '해당자금이체번호가 없음- 일자,번호확인'],
            ['code' => '750', 'message' => '해당전문번호 없음'],
            ['code' => '751', 'message' => '해당정보 없음'],
            ['code' => '752', 'message' => '해당조회일에 거래가 없습니다'],
            ['code' => '753', 'message' => '해당지점 처리불가'],
            ['code' => '754', 'message' => '해당회차 환율 미고시'],
            ['code' => '755', 'message' => '활동좌아님'],
            ['code' => '756', 'message' => '해지기관'],
            ['code' => '757', 'message' => '해지된 납부자번호'],
            ['code' => '758', 'message' => '해지,이관,잡좌,잡수입계좌'],
            ['code' => '759', 'message' => '현금카드 분실상태임'],
            ['code' => '760', 'message' => '형식 불비 (수표부도 사유)'],
            ['code' => '761', 'message' => '환율원장상태불량,상태=SFHXER01,RC,KEY=X'],
            ['code' => '762', 'message' => '황색거래자는 거래할 수 없습니다'],
            ['code' => '763', 'message' => '황색업체는 등록할 수 없습 니다'],
            ['code' => '764', 'message' => '회계단위 오류입니다．'],
            ['code' => '765', 'message' => '회선 장애 중'],
            ['code' => '766', 'message' => '후송일 거래를 할 수 없습니다'],
            ['code' => '767', 'message' => '휴일에는 거래하실 수 없습니다'],
            ['code' => '768', 'message' => 'AMWAY 결제계좌 해제후 거래하세요'],
            ['code' => '769', 'message' => 'CD 공동망 이용수수료 부족입니다'],
            ['code' => '770', 'message' => 'CD 공동망 입금건수 초과 (일 9999 건)'],
            ['code' => '771', 'message' => 'CENTER 계좌에 대한 거래불가'],
            ['code' => '772', 'message' => 'CHECK DIGIT 에러'],
            ['code' => '773', 'message' => 'CHECK TYPE 누락'],
            ['code' => '774', 'message' => 'CIF 상태 오류입니다. (NOT= 1,16,17)'],
            ['code' => '775', 'message' => 'CMS 업무 입금 불가 (개시전, 마감후)'],
            ['code' => '776', 'message' => 'CMS 업무 입금 불가 (개시전, 마감후)'],
            ['code' => '777', 'message' => 'CMS 계좌인데 CMS Code 가 없음'],
            ['code' => '778', 'message' => 'CMS 계좌인데 CMS Code 가 틀림'],
            ['code' => '779', 'message' => 'CMS 코드를 CMS 번호란에 입력하세요'],
            ['code' => '780', 'message' => 'CMS 과목이 아닙니다'],
            ['code' => '781', 'message' => 'CONPUT ERROR'],
            ['code' => '782', 'message' => 'DBBXC ERROR'],
            ['code' => '783', 'message' => 'EB-ICHE-HIS 에 타행건수가 0 입니다'],
            ['code' => '784', 'message' => 'ERROR/RESP 코드 오류'],
            ['code' => '785', 'message' => 'ESSAGE ID 오류입니다．'],
            ['code' => '786', 'message' => 'FIELD 번호 xxx FORMAT 오류'],
            ['code' => '787', 'message' => 'INF-FILE 갱신대상 거래가 아닙니다'],
            ['code' => '788', 'message' => 'INPUT ERROR'],
            ['code' => '789', 'message' => 'LAG 오류 입니다．'],
            ['code' => '790', 'message' => '현재 라인 장애중입니다'],
            ['code' => '791', 'message' => 'Magnetic Stripe 기록 오류'],
            ['code' => '792', 'message' => 'Message 코드 오류'],
            ['code' => '793', 'message' => 'NET 수탁은 통장을 사용할 수 없습니다'],
            ['code' => '794', 'message' => '프로그램 오류입니다'],
            ['code' => '795', 'message' => 'PS0066 READ ERROR 입니다'],
            ['code' => '796', 'message' => 'REAL-TIME F/B 미등록 계좌'],
            ['code' => '797', 'message' => 'REAL-TIME F/B 오류'],
            ['code' => '798', 'message' => 'REAL-TIME F/B 원거래 전문이 없음'],
            ['code' => '799', 'message' => 'ST203 오류,전산정보부로 연락하세요'],
            ['code' => '800', 'message' => 'ST283 채번 TABLE 오류'],
            ['code' => '801', 'message' => '주민사업자길이오류'],
            ['code' => '802', 'message' => '시스템 KEY 미등록'],
            ['code' => '803', 'message' => 'TH 전문과 EB-HIS 의 타행처리번호가 불일치'],
            ['code' => '804', 'message' => 'TH-ER-FILE 장애'],
            ['code' => '805', 'message' => 'TH 전문과 EB-HIS 의 타행처리번호가 불일치'],
            ['code' => '806', 'message' => '관련업무 아님'],
            ['code' => '807', 'message' => '일일 사용회수가 초과된 회원 입니다'],
            ['code' => '808', 'message' => '지점수수료청구내역생성오류'],
            ['code' => '809', 'message' => '입출내역생성오류'],
            ['code' => '810', 'message' => '복기부호 누락'],
            ['code' => '811', 'message' => '입금계좌 마감후거래로 금일입금불가능함'],
            ['code' => '812', 'message' => '지급계좌 마감후거래로 금일지급불가능함'],
            ['code' => '813', 'message' => '제한시간내 응답없습니다(１분)'],
            ['code' => '814', 'message' => '이체 가능시간이 경과 됐읍니다'],
            ['code' => '815', 'message' => '증권자금이체 서비스 미신청 업체입니다'],
            ['code' => '816', 'message' => '증권회사 모계좌이므로 입금할 수 없음'],
            ['code' => '817', 'message' => '불량채권 편입계좌'],
            ['code' => '818', 'message' => '가족회원 미등록회워'],
            ['code' => '819', 'message' => '개설은행 수신전문 오류'],
            ['code' => '820', 'message' => '개설은행에서 취소 또는 입금이체 처리중'],
            ['code' => '821', 'message' => '해당전문번호 없음'],
            ['code' => '822', 'message' => '거래정지 없음'],
            ['code' => '823', 'message' => '금액검증부호 오류'],
            ['code' => '824', 'message' => '대행기관 개시이전'],
            ['code' => '825', 'message' => '대행기관 업무종료'],
            ['code' => '826', 'message' => '대행기관 장애'],
            ['code' => '827', 'message' => '마감전 정상거래, 유효성코드 갱신요망'],
            ['code' => '828', 'message' => '마감후 정상거래. 유효성코드 갱신요망'],
            ['code' => '829', 'message' => '모계좌한도부족'],
            ['code' => '830', 'message' => '법인카드 현금서비스 불가'],
            ['code' => '831', 'message' => '불입금 상이 (1 회 불입 단위가 있는'],
            ['code' => '832', 'message' => '불입금 상이 (1 회 불입단위가 있는 경우)'],
            ['code' => '833', 'message' => '사고신고 접수 (분실. 도난. 피사취)'],
            ['code' => '834', 'message' => '수신전문 오류'],
            ['code' => '835', 'message' => '수취계좌 예금한도 초과'],
            ['code' => '836', 'message' => '수취인 계좌 입금 한도 초과'],
            ['code' => '837', 'message' => '수취조회후 수취계좌 상태 변화'],
            ['code' => '838', 'message' => '순채무한도 초과'],
            ['code' => '839', 'message' => '예금잔액 부족'],
            ['code' => '840', 'message' => '원거래 불명'],
            ['code' => '841', 'message' => '위/변조 카드'],
            ['code' => '842', 'message' => '유효성코드 갱신요망'],
            ['code' => '843', 'message' => '인감분실'],
            ['code' => '844', 'message' => '입금이체 의뢰필 (가치환불 처리필)'],
            ['code' => '845', 'message' => '전자화폐 가치저장 안됨(거래시작 BIT 해제)'],
            ['code' => '846', 'message' => '전자화폐 가치저장/환불 복구거래요망'],
            ['code' => '847', 'message' => '전자화폐 가치저장/환불복구 불가'],
            ['code' => '848', 'message' => '전자화폐 거래일련번호 상이'],
            ['code' => '849', 'message' => '전자화폐 서명값 상이'],
            ['code' => '850', 'message' => '전자화폐 알고리즘 ID 상이'],
            ['code' => '851', 'message' => '해당내용 없음'],
            ['code' => '852', 'message' => '전자화폐 키버젼 상이 (파라메터 갱신요망)'],
            ['code' => '853', 'message' => '정상 (마감점 거래)'],
            ['code' => '854', 'message' => '정상 (마감후 거래)'],
            ['code' => '855', 'message' => '종료처리 중'],
            ['code' => '856', 'message' => '중복거래 발생'],
            ['code' => '857', 'message' => '지급가능잔액 부족 (타점권 미결)'],
            ['code' => '858', 'message' => '주민/사업자번호 상이'],
            ['code' => '859', 'message' => '취급은행 사용불가'],
            ['code' => '860', 'message' => '카드발급 미등록'],
            ['code' => '861', 'message' => '통장분실'],
            ['code' => '862', 'message' => '파라메터 갱신 실패'],
            ['code' => '863', 'message' => '해당 계정 마감후 입금불가'],
            ['code' => '864', 'message' => '현금서비스 월간이용한도 초과'],
            ['code' => '865', 'message' => '확인거래 요망 (3 행이체 무응답)'],
            ['code' => '866', 'message' => 'HARDWARE 장애(취급은행의 지점,회선 DOWN)'],
            ['code' => '867', 'message' => '지로납부계좌 변경시 구계좌입력요'],
            ['code' => '868', 'message' => '현금카드상태가 활동일 경우만 사고취소거'],
            ['code' => '869', 'message' => '현금카드상태가 사고인 경우만 해지회수거'],
            ['code' => '870', 'message' => '명의도용 고객차단'],
            ['code' => '871', 'message' => '해지신청시 계좌번호 불일치'],
            ['code' => '872', 'message' => '신규신청불가'],
            ['code' => '873', 'message' => '이중신청(동일납부자&동일계좌)'],
            ['code' => '874', 'message' => '이중신청(동일납부자&상이계좌)'],
            ['code' => '875', 'message' => '징수기관 임의해지'],
            ['code' => '876', 'message' => '자동이체 해지(영업점)'],
            ['code' => '877', 'message' => '자동이체 해지(업체)'],
            ['code' => '880', 'message' => '선물사에 위험고지등록후 계좌개설가능'],
            ['code' => '897', 'message' => '위탁계좌 장기 미사용 고객.'],
            ['code' => '898', 'message' => '해당기관 선물계좌는 위탁계좌개설후 개설'],
            ['code' => '899', 'message' => '대표계좌 한도초과입니다.'],
            ['code' => '900', 'message' => '암호화 오류'],
            ['code' => '901', 'message' => '이미 거래완료 되었습니다.'],
            ['code' => '902', 'message' => '처리 PROGRAM 에서 오류가 발생하였습니다.'],
            ['code' => '903', 'message' => '시스템 장애발생으로 거래불가 합니다.'],
            ['code' => '904', 'message' => '제휴은행 시스템 장애발생으로 거래불가'],
            ['code' => '905', 'message' => '시스템 장애발생으로 거래불가 합니다.'],
            ['code' => '906', 'message' => '제휴은행 통신장애 발생으로 거래불가'],
            ['code' => '907', 'message' => '통신장애 발생으로 거래불가 합니다.'],
            ['code' => '908', 'message' => '통신 SERVER 전문접수 오류.'],
            ['code' => '909', 'message' => '업무 미개시입니다.'],
            ['code' => '910', 'message' => '취급점 단말기 오류. 단말상태를 확인'],
            ['code' => '911', 'message' => '거래를 할 수 없는 기관입니다. 확인'],
            ['code' => '912', 'message' => '제휴은행 원장상태오류.'],
            ['code' => '913', 'message' => '거래 단말 상태 오류'],
            ['code' => '914', 'message' => '1 회 거래한도 초과입니다.'],
            ['code' => '915', 'message' => '금일 한도초과입니다.'],
            ['code' => '916', 'message' => '거래가능한 기관이 아닙니다.'],
            ['code' => '917', 'message' => '본부부서 자금거래 불가합니다.'],
            ['code' => '918', 'message' => '계좌번호 오류 입니다.'],
            ['code' => '919', 'message' => '미등록 계좌번호 입니다. 확인후 거래'],
            ['code' => '920', 'message' => '사용할 수 없는 계좌번호 입니다.'],
            ['code' => '921', 'message' => '과목코드 오류 입니다'],
            ['code' => '922', 'message' => '취급점 한도약정상태 오류'],
            ['code' => '923', 'message' => '개설점 한도초과로 거래불가'],
            ['code' => '924', 'message' => '개설점 한도약정상태 오류'],
            ['code' => '928', 'message' => '카드번호 오류입니다.'],
            ['code' => '929', 'message' => '전문 상태 오류'],
            ['code' => '930', 'message' => '지로정보오류 (타행계좌번호 확인요망)'],
            ['code' => '931', 'message' => '업무종료예고로신규거래 불가.'],
            ['code' => '932', 'message' => '업무종료로 금일 거래불가'],
            ['code' => '933', 'message' => '정산완료 금일거래 불가'],
            ['code' => '934', 'message' => '업무개시 상태오류'],
            ['code' => '935', 'message' => '업무미 개시상태 오류'],
            ['code' => '936', 'message' => '업무종료예고 상태 오류'],
            ['code' => '937', 'message' => '업무종료 상태 오류'],
            ['code' => '938', 'message' => '업무정산 상태 오류'],
            ['code' => '939', 'message' => '업무재개시 상태 오류'],
            ['code' => '940', 'message' => '장애상태 오류'],
            ['code' => '997', 'message' => '주민번호길이오류'],
            ['code' => '9XX', 'message' => 'FORMAT ERROR'],
            ['code' => 'AHS', 'message' => '원거래 응답처리시 오류'],
            ['code' => 'DBE', 'message' => 'DB 연결 장애'],
            ['code' => 'F04', 'message' => '해당항목정확히세트요망'],
            ['code' => 'F15', 'message' => '전문포맷오류'],
            ['code' => 'FXX', 'message' => '전문상태확인'],
            ['code' => 'TIM', 'message' => '정상/불능확인불가 은행확인요망'],
            ['code' => 'TTT', 'message' => '트랜잭션오류'],
            ['code' => 'TXX', 'message' => 'DB 입력오류'],
            ['code' => 'X19', 'message' => '업체 오류응답(송금계좌가 가상계좌임)'],
        ];
        $idx = array_search($error_code, array_column($errors, 'code'));
        return $idx !== false ? $errors[$idx]['message'] : $message;
    }
}
