export const dozn_error_codes = [
    { code: "VTIM", message: "타임아웃이 발생하였습니다", retry: 'O'},
    { code: "0011", message: "타임아웃이 발생하였습니다", retry: 'O'},
    { code: 'E0001', message : '서버 내부에서 처리 중 에러가 발생했습니다. 전자서명 준비 API부터 다시 진행하세요.', retry: ''},
    { code: 'E0002', message : '서버 점검 중입니다. 잠시 후 다시 시도해주세요.', retry: ''},
    { code: 'E1001', message : '필수 인자가 포함되지 않았습니다.', retry: ''},
    { code: 'E1002', message : '해당 API에 대한 요청 권한이 없습니다.', retry: ''},
    { code: 'E1003', message : '허용된 요청 회수를 초과하였습니다.', retry: ''},
    { code: 'E1004', message : 'Authorization 헤더(Header)가 없습니다.', retry: ''},
    { code: 'E1005', message : 'Settle-Id 헤더(Header)가 없습니다.', retry: ''},
    { code: 'E2001', message : '존재하지 않는 카카오계정입니다.', retry: ''},
    { code: 'E2002', message : '사용자 식별 정보와 카카오 계정 정보가 일치하지 않습니다. 사용자 식별정보 확인 후 재호출해주세요. 동일한 증상이 반복될 경우 서비스 이용이 불가합니다.', retry: ''},
    { code: 'E2003', message : 'tx_id에 대한 정보가 존재하지 않습니다. 전자서명 준비 API를 재호출해주세요.', retry: ''},
    { code: 'E2004', message : '전자서명 요청하기 API가 정상 처리된 이후에 다시 호출되었습니다.', retry: ''},
    { code: 'E2005', message : '카카오계정의 상태가 휴먼, 제재, 탈퇴 보호 상태입니다.', retry: ''},
    { code: 'E2006', message : '전자서명을 먼저 완료해주세요.', retry: ''},
    { code: 'E2007', message : '이미 검증된 전자서명입니다.', retry: ''},
    { code: 'E2008', message : '이미 요청된 전자서명입니다.', retry: ''},
    { code: 'E2009', message : '사용자가 채널 메시지를 수신거부하여 진행할 수 없습니다.', retry: ''},
    { code: 'E2010', message : '카카오계정에 본인 인증 정보가 없습니다.', retry: ''},
    { code: 'E2011', message : '동일 CI로 가입된 카카오계정이 2개 이상입니다.', retry: ''},
    { code: 'E2012', message : 'documents의 순서가 document_tx_id와 잘못 매핑되었습니다.', retry: ''},
    { code: 'E2013', message : '만료된 전자서명입니다.', retry: ''},
    { code: 'E3001', message : '상품코드에 대한 권한이 없습니다.', retry: ''},
    { code: 'E3002', message : '상품코드가 존재하지 않습니다.', retry: ''},
    { code: 'E3003', message : '요청 파라미터에 대한 계약 내용이 존재하지 않습니다.', retry: ''},
    { code: 'E3004', message : '데이터 포맷이 맞지 않거나 데이터가 계약 내용과 다릅니다.', retry: ''},
    { code: 'D101', message : '지원하지 않는 Content-Type 입니다.', retry: ''},
    { code: 'D102', message : '허용하지 않는 HTTP Method 입니다.', retry: ''},
    { code: 'D103', message : '잘못된 경로(Path) 입니다.', retry: ''},
    { code: 'D104', message : 'Settle-Id가 두 개 이상 존재하나 Header에 값이 존재하지 않습니다.', retry: ''},
    { code: 'D203', message : '요청 Body가 빈 값 혹은 잘못된 형식입니다.', retry: ''},
    { code: 'D204', message : '유효하지 않은 필드 값입니다.', retry: ''},
    { code: 'D205', message : '유효하지 않은 JSON 형식입니다.', retry: ''},
    { code: 'D901', message : '타임아웃이 발생하였습니다.', retry: ''},
    { code: 'D977', message : '정의되지 않은 데이터입니다.', retry: ''},
    { code: 'D998', message : '정의되지 않은 에러입니다.', retry: ''},
    { code: 'D999', message : '시스템 에러입니다.', retry: ''},
    { code: 'D4001', message : '전자서명 검증 API가 이미 호출되어 전자서명 검증 중입니다.', retry: ''},
    { code: 'D4002', message : '만료된 서명 id입니다. 다시 시도해주세요.', retry: ''},
]
