export const hecto_error_codes = [
    {code: 'PY11', message: '은행 점검시간', retry: 'O'},
    {code: 'PY12', message: '예치금 잔액 부족', retry: ''},
    {code: 'PY21', message: '수취인 계좌 없음', retry: ''},
    {code: 'PY31', message: '환용정보 오류', retry: ''},
    {code: 'PY41', message: '서비스용량조과', retry: ''},
    {code: 'PY42', message: '거래 불가 은행', retry: ''},
    {code: 'PY43', message: 'WLF에 의해 차단됨', retry: ''},
    {code: 'PY44', message: 'WLF대상으로 별도 승인처리 필요', retry: ''},
    {code: 'PY50', message: '중북 전문 요청', retry: ''},
    {code: 'PY51', message: '이미 취소된 거래', retry: ''},
    {code: 'PY97', message: '등록되지 않은 가맹점(메시지 확인)', retry: ''},
    {code: 'PY98', message: '유효하지 많은 요청전문(메시지 확인)', retry: ''},
    {code: 'PY99', message: '내부 시스템 오류', retry: ''},
    {code: 'VITM', message: '원전사 타임아웃', retry: 'O'},
    {code: 'P451', message : '은행기관 거래 마감시간 초과', retry: 'O'},
]
