export const welcome_error_codes = [
    {'code' : 'M001', 'message' : '해당 MERCHANT 에 가입되어 있는 USER 가 아닙니다.'},
    {'code' : 'M002', 'message' : '해당 MEMBER 를 찾을 수 없습니다.'},
    {'code' : 'M003', 'message' : 'MERCHANT 등록을 확인해주세요.'},
    {'code' : 'M004', 'message' : '해당 멤버는 USER 가 아닙니다. '},
    {'code' : 'M005', 'message' : '조회대상이 아닙니다.'},
    {'code' : 'M006', 'message' : 'MEMBER 타입을 확인해 주세요.'},
    {'code' : 'M007', 'message' : '다른 GUID 로 가입되어 있습니다.(이메일 중복)'},
    {'code' : 'M008', 'message' : '다른 GUID 로 가입되어 있습니다.(모바일 중복)'},
    {'code' : 'M009', 'message' : '해당 GUID 를 찾을 수 없습니다.'},
    {'code' : 'M010', 'message' : '차주 확인 실패'},
    {'code' : 'M011', 'message' : '동일 MERCHANT_USER 는 사용할 수 없습니다.'},
    {'code' : 'M012', 'message' : '가입성명이 동일하지 않습니다.'},
    {'code' : 'M013', 'message' : '이메일이 동일하지 않습니다.'},
    {'code' : 'M014', 'message' : '핸드폰 번호가 동일하지 않습니다.'},
    {'code' : 'M015', 'message' : '해당 MEMBER 는 MERCHANT 가 아닙니다.'},
    {'code' : 'M016', 'message' : '해당 MERCHANT 에 존재하지 않는 GUID 가 있습니다.'},
    {'code' : 'M017', 'message' : '유저간 송금 API 를 이용하실 수 없는 MEMBER 입니다.'},
    {'code' : 'M018', 'message' : '유저간 송금인증 API 를 이용하실 수 없는 MEMBER 입니다.'},
    {'code' : 'M019', 'message' : '일반 MEMBER 만 사용가능 합니다. '},
    {'code' : 'M020', 'message' : '동일한 MERCHANT_USER 가 아닙니다.'},
    {'code' : 'M021', 'message' : '동일한 MERCHANT_USER 에서만 사용가능 합니다. '},
    {'code' : 'M022', 'message' : 'MERCHANT 정보를 확인해 주세요.'},
    {'code' : 'M023', 'message' : '차주 USER 가 아닙니다.'},
    {'code' : 'M024', 'message' : 'USER 가 차주인지 확인하세요.'},
    {'code' : 'M025', 'message' : 'USER 가입시 이름, 모바일, 이메일 필드에는 공백이 들어갈 수 없습니다. '},
    {'code' : 'M026', 'message' : 'Merchant 에 등록된 Push Url 이 존재하지 않습니다.'},
    {'code' : 'M027', 'message' : '삭제할 Push Url 이 존재하지 않습니다.'},
    {'code' : 'M028', 'message' : '기존에 등록된 정보가 존재합니다.'},
    {'code' : 'M029', 'message' : '머천트 담당자는 유저로 가입할 수 없습니다.'},
    {'code' : 'M030', 'message' : '머천트 출금은행 BankId 정보 미등록상태 '},
    {'code' : 'M031', 'message' : 'mobile 인증정보가 일치하지 않습니다.'},
    {'code' : 'M032', 'message' : '송금요청을 사용할 수 없는 USER 입니다.'},
    {'code' : 'M033', 'message' : 'user 의 mobileCi 값만 update 가능합니다.'},
    {'code' : 'M034', 'message' : '동일한 mobileCi 값이 존재합니다.'},
    {'code' : 'M035', 'message' : '기존에 등록된 mobileCi 값이 존재합니다. '},
    {'code' : 'M036', 'message' : 'USER 가입시 이름, 모바일, 이메일, CI 필드에는 공백이 들어갈 수 없습니다. '},
    {'code' : 'M037', 'message' : 'mobileNo 를 확인해주세요.'},
    {'code' : 'M038', 'message' : 'mobileCi 값이 등록된 user 가 아닙니다.'},
    {'code' : 'M039', 'message' : '머천트에 등록되어 있는 대표 번호로 유저 가입이 불가합니다.'},
    {'code' : 'M040', 'message' : '유니크키가 이미 존재 합니다.'},
    {'code' : 'M041', 'message' : '이 멤버는 마이그레이션 대상멤버가 아닙니다 '},
    {'code' : 'M042', 'message' : '머천트만 수정이 가능합니다.'},
    {'code' : 'M043', 'message' : '패스워드가 일치하지 않습니다.'},
    {'code' : 'M044', 'message' : '패스워드가 인증이 필요합니다.'},
    {'code' : 'M045', 'message' : '해당 머천트는 PORTAL 머천트에 속해 있지 않은 머천트 입니다. PORTAL 에 가입해주세요. '},
    {'code' : 'M046', 'message' : '대출 실행 계좌를 먼저 등록해주세요. '},
    {'code' : 'M047', 'message' : '유니크키가 너무 깁니다. 16 자 이하로 설정해 주세요.'},
    {'code' : 'M048', 'message' : '멤버 GUID 를 확인하세요.'},
    {'code' : 'M049', 'message' : '포탈 마스터 머천트가 아닙니다. 머천트 API 키를 확인 바랍니다.'},
    {'code' : 'M050', 'message' : '모계좌 지급정지에 실패하였습니다.'},
    {'code' : 'M051', 'message' : '모계좌 지급정지에 정보조회에 실패하였습니다.(조회되지 않는 가상계좌 입니다.)'},
    {'code' : 'M052', 'message' : '멤버 이름의 길이가 초과되었습니다. 다시 입력바랍니다. 최대 10 자까지 가능합니다. '},
    {'code' : 'M053', 'message' : '인증 만료기간은 90, 180, 270, 365 만 허용합니다.'},
    {'code' : 'M054', 'message' : '담당자 이름과 번호를 지정해 주세요. '},
    {'code' : 'T001', 'message' : '고객사 시스템 참조 ID 중복입니다. '},
    {'code' : 'T002', 'message' : 'TID 를 확인하세요.'},
    {'code' : 'T003', 'message' : 'CURRENCY_TYPE 오류입니다.'},
    {'code' : 'T004', 'message' : 'PENDING 을 진행할 수 없는 상태입니다.'},
    {'code' : 'T005', 'message' : 'MAIN TRANSACTION 이 존재하지 않습니다. '},
    {'code' : 'T006', 'message' : 'orgCrrncy 는 KRW 이어야 합니다. '},
    {'code' : 'T007', 'message' : '요청해주신 TID 는 USER_PENDING 이 아닙니다.'},
    {'code' : 'T008', 'message' : '취소 불가 상태입니다.'},
    {'code' : 'T009', 'message' : '이미 생성된 거래입니다.'},
    {'code' : 'T010', 'message' : 'outerRefId 가 존재하지 않습니다.'},
    {'code' : 'T011', 'message' : 'orgCrrncy 를 확인해주세요.'},
    {'code' : 'T012', 'message' : '유저간 송금 API 를 이용하실 수 없는 멤버입니다.'},
    {'code' : 'T013', 'message' : 'USER 간 송금요청을 진행하기 위한 MERCHANT 등록을 진행하시기 바랍니다.'},
    {'code' : 'T014', 'message' : '해당 거래는 이미 릴리즈상태이므로 진행 할 수 없습니다.'},
    {'code' : 'T015', 'message' : '해당 거래는 이미 취소상태이므로 진행 할 수 없습니다.'},
    {'code' : 'T016', 'message' : '해당 거래는 MERCHANT_PENDING 거래가 아니므로 진행 할 수 없습니다.'},
    {'code' : 'T017', 'message' : '릴리즈 인증을 하지 않아 진행 할 수 없습니다.'},
    {'code' : 'T018', 'message' : '취소 인증을 하지 않아 진행 할 수 없습니다.'},
    {'code' : 'T019', 'message' : '요청한 MERCHANT 와 해당 거래에 MERCHANT 는 다르기 때문에 조회를 할 수없습니다. '},
    {'code' : 'T020', 'message' : 'PTID 가 존재하지 않습니다.'},
    {'code' : 'T021', 'message' : '요청 정보가 정확하지 않습니다.'},
    {'code' : 'T022', 'message' : '변경일자를 확인해주세요.'},
    {'code' : 'T023', 'message' : 'YYYYDDMM 형식으로 요청 바랍니다.'},
    {'code' : 'T024', 'message' : '해당 GUID 를 확인해 주세요. '},
    {'code' : 'T025', 'message' : '펜딩에 참여하지 않은 USER 가 발견되었습니다. 확인 후 다시 진행바랍니다. '},
    {'code' : 'T026', 'message' : 'BANKID 확인바랍니다.'},
    {'code' : 'T027', 'message' : '계좌주 검증 계약을 확인하세요.'},
    {'code' : 'T028', 'message' : '커런시타입을 확인해 주세요.'},
    {'code' : 'T029', 'message' : '가상 계좌주 이름을 확인바랍니다.'},
    {'code' : 'T030', 'message' : '해당 API 는 차주만 이용할 수 있습니다.'},
    {'code' : 'T031', 'message' : 'URL 정보를 확인해 주세요.'},
    {'code' : 'T032', 'message' : '전체 URL 주소를 입력해 주세요. '},
    {'code' : 'T033', 'message' : '푸시 mime 타입은 JSON 으로 요청해야합니다.'},
    {'code' : 'T034', 'message' : '해당 거래는 수정이 불가능 합니다. '},
    {'code' : 'T035', 'message' : '입출금 내역이 존재하지 않습니다.'},
    {'code' : 'T036', 'message' : '중복요청으로 인증문자 재발송이 되지 않습니다. '},
    {'code' : 'T037', 'message' : '재전송 요청 거래를 찾을 수 없습니다.'},
    {'code' : 'T038', 'message' : '투자내역이 존재하지 않습니다.'},
    {'code' : 'T039', 'message' : '검색일자는 YYYYMMDD 로 요청해주세요.'},
    {'code' : 'T040', 'message' : '검색일자의 입출금 내역이 존재하지 않습니다. '},
    {'code' : 'T041', 'message' : 'BankOwnerName 을 10 자 이하로 입력해주세요.'},
    {'code' : 'T042', 'message' : 'MemAccntno 입력정보 오류.'},
    {'code' : 'T043', 'message' : 'bankId 및 계좌번호를 확인해주세요.'},
    {'code' : 'T044', 'message' : 'SendName 을 10 자 이하로 입력해주세요.'},
    {'code' : 'T045', 'message' : 'BankOwnerName 을 2 자 이상 입력해주세요.'},
    {'code' : 'T046', 'message' : '입금 내역이 존재하지 않습니다.'},
    {'code' : 'T047', 'message' : 'mobileCi 값을 확인해주세요.'},
    {'code' : 'T048', 'message' : '인증단어를 확인해주세요.'},
    {'code' : 'T049', 'message' : '요청데이터를 확인해주세요.'},
    {'code' : 'T050', 'message' : 'PendingName 을 확인해주세요.'},
    {'code' : 'T051', 'message' : 'PendingRate 을 확인해주세요.'},
    {'code' : 'T052', 'message' : 'ReturnDttm(상환일자)을 확인해주세요.'},
    {'code' : 'T053', 'message' : '이미 취소된 거래입니다.'},
    {'code' : 'T054', 'message' : 'ARS 인증을 위한 전화번호가 존재하지 않습니다.'},
    {'code' : 'T055', 'message' : 'arsType 은 필수값입니다.'},
    {'code' : 'T056', 'message' : '이미 처리된 거래건 입니다.'},
    {'code' : 'T057', 'message' : 'parameter 를 확인해주세요.'},
    {'code' : 'T058', 'message' : '다른 GUID 의 거래정보는 확인 할 수 없습니다.'},
    {'code' : 'T059', 'message' : '분할송금데이터가 존재하지 않습니다.'},
    {'code' : 'T060', 'message' : '등록된 URL 이 없습니다. POST 로 요청해주세요.'},
    {'code' : 'T061', 'message' : 'remark 는 필수값입니다.'},
    {'code' : 'T062', 'message' : 'Member 의 BANKID 를 확인바랍니다. '},
    {'code' : 'T063', 'message' : 'Member 의 성명이 존재하지 않습니다. '},
    {'code' : 'T064', 'message' : '출금계좌가 등록되지 않은 상태입니다.'},
    {'code' : 'T065', 'message' : '머천트는 펜딩의 차주로 불가능합니다.'},
    {'code' : 'T066', 'message' : '송금을 진행할 수 없습니다.'},
    {'code' : 'T067', 'message' : '이미 생성된 채권거래가 있습니다.'},
    {'code' : 'T068', 'message' : '요청금액이 너무 큽니다. 확인바랍니다.'},
    {'code' : 'T069', 'message' : '생성된 채권거래가 없습니다. TID 를 확인해주세요.'},
    {'code' : 'T070', 'message' : '최초 채권소유자만 해당 API 를 사용할 수 있습니다.'},
    {'code' : 'T071', 'message' : '채권소유자를 확인해 주세요.'},
    {'code' : 'T072', 'message' : '본인의 채권은 구매할 수 없습니다. '},
    {'code' : 'T073', 'message' : '처리중인 거래입니다. 잠시후 다시 시도해 주세요.'},
    {'code' : 'T074', 'message' : '요청하신 TID 에 금액이 일치하지 않습니다.'},
    {'code' : 'T075', 'message' : '상환금액이 부족하여 과입금 반환이 불가능합니다. '},
    {'code' : 'T076', 'message' : '트랜잭션 머천트가 일치하지 않습니다.'},
    {'code' : 'T077', 'message' : '프로토콜은 https 로 시작하여야 합니다. '},
    {'code' : 'T078', 'message' : '출금 서비스가 제한 되었습니다. 업체에 문의해 주시기 바랍니다.'},
    {'code' : 'W001', 'message' : '출금자 지정이 잘못되었습니다.'},
    {'code' : 'W002', 'message' : '출금을 진행할 수 없습니다. CURRENCY_TYPE 을 확인하세요.'},
    {'code' : 'W003', 'message' : '출금요청 금액을 확인하세요.'},
    {'code' : 'W004', 'message' : '출금계좌 정보가 동일하지 않습니다.'},
    {'code' : 'W005', 'message' : '차주의 출금 가능 금액을 초과하였습니다. '},
    {'code' : 'W006', 'message' : '출금요청 은행코드(bankId)를 확인해 주세요.'},
    {'code' : 'W007', 'message' : '출금요청 계좌주명(BankOwnerName)을 확인해 주세요.'},
    {'code' : 'W008', 'message' : '출금요청 계좌번호(memAccntno)를 확인해 주세요.'},
    {'code' : 'W009', 'message' : '출금계좌가 등록되어 있어야만 가상계좌 발급이 가능합니다.'},
    {'code' : 'W010', 'message' : '가상계좌를 발급받을 수취인과 출금계좌 예금주명이 일치하지 않습니다.'},
    {'code' : 'W011', 'message' : '출금계좌가 등록되지 않았거나 검색할 수 없는 MEMBER 입니다.'},
    {'code' : 'W012', 'message' : '출금계좌가 등록되어 있는 상태입니다.'},
    {'code' : 'W013', 'message' : '인증되지 않은 출금계좌가 등록되어 있습니다. 출금계좌 번호변경 또는 출금계좌 인증을완료해 주세요. '},
    {'code' : 'W014', 'message' : '예금주명 오류'},
    {'code' : 'W015', 'message' : '동일 출금계좌가 등록되어 있어 재등록 할 수 없습니다.'},
    {'code' : 'W016', 'message' : '출금계좌가 등록되지 않은 상태입니다. 출금계좌 등록서비스를 이용해 주세요.'},
    {'code' : 'W017', 'message' : '출금계좌 등록 오류입니다. 상점으로 문의바랍니다. '},
    {'code' : 'W018', 'message' : '머천트의 출금계좌 오류. 웰컴페이먼츠로 확인요망. '},
    {'code' : 'W019', 'message' : '머천트의 출금계좌 미등록상태. 웰컴페이먼츠로 확인요망. '},
    {'code' : 'W020', 'message' : '머천트의 출금계좌 미인증상태. 웰컴페이먼츠로 확인요망. '},
    {'code' : 'W021', 'message' : '등록하려는 예금주 성명과 멤버의 성명이 다릅니다.'},
    {'code' : 'W022', 'message' : '계좌번호만 입력해주세요.'},
    {'code' : 'W023', 'message' : '은행업무 점검시간 입니다. (점검시간 : 23:30~00:30)'},
    {'code' : 'W024', 'message' : '존재하지 않는 정보입니다.'},
    {'code' : 'W025', 'message' : 'User 의 출금계좌가 미인증 상태입니다. '},
    {'code' : 'W026', 'message' : '머천트의 출금계좌가 미인증 상태입니다.'},
    {'code' : 'W027', 'message' : 'FromUser 의 출금계좌가 미인증 상태입니다. '},
    {'code' : 'W028', 'message' : 'ToUser 의 출금계좌가 미인증 상태입니다. '},
    {'code' : 'W029', 'message' : '계좌인증상태 확인바랍니다.'},
    {'code' : 'W030', 'message' : '수취인의 가상계좌 또는 지갑이 생성되어 있지 않습니다. 자세한 내용은 문의바랍니다. '},
    {'code' : 'W031', 'message' : '계좌번호 길이가 초과되었습니다. 다시 확인 바랍니다.'},
    {'code' : 'W032', 'message' : '출금계좌 인증은 하루에 3 번만 가능합니다. 내일 다시 시도해 주세요. '},
    {'code' : 'B001', 'message' : '금액오류'},
    {'code' : 'B002', 'message' : '송금요청 금액오류입니다.'},
    {'code' : 'B003', 'message' : '송금가능 금액을 초과하였습니다.'},
    {'code' : 'B004', 'message' : '지급가능 금액을 초과하였습니다.'},
    {'code' : 'B005', 'message' : '차주의 잔액을 확인하세요.'},
    {'code' : 'B006', 'message' : '유저는 잔액확인이 불가능 합니다.'},
    {'code' : 'B007', 'message' : '출금을 진행할 수 없습니다. 출금통화를 확인하세요.'},
    {'code' : 'B008', 'message' : '잔액확인이 불가능 합니다.'},
    {'code' : 'B009', 'message' : '거래 금액을 확인하세요.'},
    {'code' : 'V001', 'message' : '인증실패입니다.'},
    {'code' : 'V002', 'message' : '인증상태 오류'},
    {'code' : 'V003', 'message' : '인증을 받아야만 투자를 진행할 수 있습니다.'},
    {'code' : 'V004', 'message' : '이미 90 일 인증이 되어있습니다. '},
    {'code' : 'V005', 'message' : '해당 멤버는 인증멤버가 아닙니다.'},
    {'code' : 'V006', 'message' : '인증이 완료되지 않았습니다. 기간이 만료되었다면 재인증을 진행해야 합니다.'},
    {'code' : 'V007', 'message' : '해당 멤버는 유저이므로 유저 인증을 진행해 주세요.'},
    {'code' : 'V008', 'message' : '해당 멤버는 인증 갱신이 불가능 합니다. 인증 등록을 다시 진행해 주세요. '},
    {'code' : 'V009', 'message' : '90 일 인증을 받지 않았습니다. 먼저 90 일 인증을 진행해 주세요. '},
    {'code' : 'V010', 'message' : '포탈 멤버가 90 일 인증을 받지 않았습니다. 포탈 멤버의 90 일 인증을 먼저진행해주세요.'},
    {'code' : 'V011', 'message' : '마스터 포탈 멤버의 GUID 를 확인해 주세요'},
    {'code' : 'V012', 'message' : '이미 포탈멤버의 가입이 되어있습니다.'},
    {'code' : 'A001', 'message' : '출금계좌가 미인증 상태입니다.'},
    {'code' : 'A002', 'message' : '가상계좌 발급내역이 존재하지 않습니다.'},
    {'code' : 'A003', 'message' : 'FROM GUID 의 가상계좌 생성을 진행해야 합니다.'},
    {'code' : 'A004', 'message' : 'TO GUID 의 가상계좌 생성을 진행해야 합니다.'},
    {'code' : 'A005', 'message' : 'MERCHANT 의 가상계좌 생성을 진행해야 합니다.'},
    {'code' : 'A006', 'message' : '가상계좌번호가 등록되지 않았습니다.'},
    {'code' : 'A007', 'message' : '가상계좌를 발급할 수 없는 상태입니다. '},
    {'code' : 'A008', 'message' : '가상계좌 발급요청이 잘못되었습니다.'},
    {'code' : 'A009', 'message' : '가상계좌가 발급된 상태입니다.'},
    {'code' : 'A010', 'message' : '가상계좌를 발급받아야 내역조회를 하실 수 있습니다.'},
    {'code' : 'A011', 'message' : '이익금 출금계좌가 미인증 상태입니다.'},
    {'code' : 'A012', 'message' : '가상계좌가 발급되지 않은 상태입니다.'},
    {'code' : 'A013', 'message' : '차주의 출금계좌를 확인하시기 바랍니다.'},
    {'code' : 'A014', 'message' : '입금제어해제 가능횟수를 초과하였습니다.'},
    {'code' : 'A015', 'message' : '이미 가상계좌의 상태가 입금정지상태 입니다. '},
    {'code' : 'A016', 'message' : '이미 가상계좌의 상태가 입금정지 해제상태 입니다.'},
    {'code' : 'A017', 'message' : '가상계좌번호를 확인 바랍니다.'},
    {'code' : 'A018', 'message' : '가상계좌가 존재하지 않습니다. 다시 시도해 주세요.'},
    {'code' : 'P001', 'message' : 'P2P MEMBER 는 해당 API 를 이용할 수 없습니다.'},
    {'code' : 'P002', 'message' : 'API 사용이 잘못되었습니다.'},
    {'code' : 'P003', 'message' : '일반 MEMBER 는 해당 API 를 이용할 수 없습니다.'},
    {'code' : 'R001', 'message' : '상환 ID 가 존재하지 않습니다. '},
    {'code' : 'R002', 'message' : '상환가능한 MEMBER 가 아닙니다.'},
    {'code' : 'R003', 'message' : '상환금액 오류'},
    {'code' : 'R004', 'message' : '해당 RETURNID 를 검색할 수 있는 가맹점이 아닙니다.'},
    {'code' : 'R005', 'message' : '상환 ID 가 잘못되었습니다.'},
    {'code' : 'R006', 'message' : '동일 상환 ID 에 대한 인증처리가 완료 또는 종료되지 않았습니다. '},
    {'code' : 'R007', 'message' : '요청 PTID 로 검색할 수 있는 상환 ID(returnId)가 존재하지 않습니다. '},
    {'code' : 'R008', 'message' : '해당 PTID 를 검색할 수 있는 가맹점이 아닙니다.'},
    {'code' : 'R009', 'message' : '상환정보가 일치하지 않습니다.'},
    {'code' : 'E001', 'message' : '거래 실패'},
    {'code' : 'E002', 'message' : '상점관리자에 가입이 안되어 있습니다. 확인 바랍니다'},
    {'code' : 'E003', 'message' : '상점관리자에 가입이 안되어 있습니다. 확인 바랍니다.'},
    {'code' : 'E004', 'message' : 'INTERNAL_SERVER_ERROR'},
    {'code' : 'E005', 'message' : 'BAD_REQUEST'},
    {'code' : 'E006', 'message' : 'REQUEST BODY 의 처리 가능한 LIST 개수를 초과하였습니다.'},
    {'code' : 'E007', 'message' : '수취조회에 실패 했습니다. 잠시후 다시 시도해주세요.'},
    {'code' : 'E008', 'message' : 'REQUEST BODY 정보가 없습니다.'},
    {'code' : 'E009', 'message' : '정보를 조회 할 수 없습니다. 다시 시도해주세요.'},
    {'code' : 'E010', 'message' : '파일을 찾을 수 없습니다. 다시 시도해주세요.'},
    {'code' : 'REWARD001', 'message' : '리워드 잔액이 부족하여 지급 할 수 없습니다.'},
    {'code' : 'REWARD002', 'message' : '리워드 DB 처리 에러.'},
    {'code' : 'AWS0001', 'message' : '파일 업로드에 실패했습니다.'},
    {'code' : 'AWS0002', 'message' : '파일 업로드에 실패했습니다.(허용하는 확장자 이미지가 아닙니다.)'},
    {'code' : 'AWS0003', 'message' : 'AmazonS3 인증에 실패했습니다.'},
    {'code' : 'AWS0004', 'message' : '파일 삭제에 실패했습니다.'},
    {'code' : 'L001', 'message' : '세션 정보가 없습니다.'},
    {'code' : 'ARS_E001', 'message' : 'ARS 요청 데이터 데이터베이스 등록에 실패했습니다.'},
    {'code' : 'ARS_E002', 'message' : 'ARS 인증에 실패 했습니다.'},
    {'code' : 'MAIL_E001', 'message' : '이메일 발송 정보 등록에 실패했습니다.'},
]
